// Project: Inventor Relocation
// Creation Date: 10/02/2024
// Last Update: 10/02/2024
// Author: Laura Arnemann 
// Goal: Cleaning government and university entities, based on dorn 


gen assignee_std = strupper(disambig_assignee_organization)

* Also need to clean the corporate assignees so that the other parts of the code will work
gen asg_corp=0
qui replace asg_corp = 1 if strpos(assignee_std," & BRO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," & BROTHER ")>0
qui replace asg_corp = 1 if strpos(assignee_std," & C ")>0
qui replace asg_corp = 1 if strpos(assignee_std," & CIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," & CO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," & FILS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," & PARTNER ")>0
qui replace asg_corp = 1 if strpos(assignee_std," & SOEHNE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," & SOHN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," & SON ")>0
qui replace asg_corp = 1 if strpos(assignee_std," & SONS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," & ZN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," & ZONEN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," A ")>0
qui replace asg_corp = 1 if strpos(assignee_std," A G ")>0
qui replace asg_corp = 1 if strpos(assignee_std," A RL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," A S ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AANSPRAKELIJKHEID ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AB ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ACTIEN GESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ACTIENGESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AD ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ADVIESBUREAU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AG & CO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AGG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AGSA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AK TIEBOLAGET ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKIEBOLAG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKIEBOLG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKIENGESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKITENGESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKITIEBOLAG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKLIENGISELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKSJESELSKAP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKSJESELSKAPET ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKSTIEBOLAGET ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTAINGESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTEIBOLAG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTEINGESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIBOLAG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIE BOLAGET ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIEBDAG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIEBLOAG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIEBOALG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIEBOALGET ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIEBOCAG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIEBOLAC ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIEBOLAF ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIEBOLAG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIEBOLAGET ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIEBOLAQ ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIEBOLOG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIEGBOLAG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIEGESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIEGOLAGET ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIELBOLAG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIEN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIEN GESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENBOLAG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENBOLAGET ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENEGESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENEGSELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGEGESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESCELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESELL SCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESELLCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESELLESCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESELLESHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESELLS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESELLSCAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESELLSCGAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESELLSCHART ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESELLSCHATT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESELLSCHGT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESELLSCHRAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESELLSHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESELLSHAT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESELLSHCAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESELSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESESCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESILLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESLLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESSELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGESSELSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGSELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENGTESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIENRESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIESELSKAB ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTIESELSKABET ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTINGESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTSIONERNAYA KOMPANIA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTSIONERNO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTSIONERNOE OBCHESTVO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTSIONERNOE OBSCHEDTVO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTSIONERNOE OBSCNESTVO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTSIONERNOE OBSHESTVO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTSIONERNOE OSBCHESTVO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AKTSIONERNOEOBSCHESTVO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ALTIENGESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AMBA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AND SONS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ANDELSSELSKABET ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ANLAGENGESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," APPARATEBAU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," APPERATEBAU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ARL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ASA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ASKTIENGESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ASOCIADOS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ASSCOIATES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ASSOCIADOS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ASSOCIATE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ASSOCIATED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ASSOCIATES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ASSOCIATI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ASSOCIATO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ASSOCIES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ASSSOCIATES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ATELIER ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ATELIERS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ATIBOLAG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ATKIEBOLAG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ATKIENGESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," AVV ")>0
qui replace asg_corp = 1 if strpos(assignee_std," B ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BANK ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BANQUE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BEDRIJF ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BEDRIJVEN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BEPERK ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BEPERKTE AANSPREEKLIJKHEID ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BESCHRAENKTER HAFTUNG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BESCHRANKTER ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BESCHRANKTER HAFTUNG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BESLOTENGENOOTSCHAP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BESLOTENVENNOOTSCHAP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BETRIEBE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BMBH ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BRANDS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BROS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BUSINESS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BV ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BV: ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BV? ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BVBA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BVBASPRL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BVIO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," BVSA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," C{OVERSCORE O}RP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CAMPAGNIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CAMPANY ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CC ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CMOPANY ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CO OPERATIVE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CO OPERATIVES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CO: ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COFP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COIRPORATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMANY ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMAPANY ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMERCIAL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMERCIO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMMANDITE SIMPLE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMMERCIALE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMMERCIALISATIONS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMNPANY ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMPAGNE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMPAGNI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMPAGNIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMPAGNIN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMPAGNY ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMPAIGNIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMPAMY ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMPANAY ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMPANH ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMPANHIA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMPANIA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMPANIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMPANIES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMPANY ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMPAY ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMPNAY ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMAPNY ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMPNY ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COMPORATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CONSORTILE PER AZIONE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CONSORZIO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CONSTRUCTIONS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CONSULTING ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CONZORZIO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COOEPERATIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COOEPERATIEVE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COOEPERATIEVE VERENIGING ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COOEPERATIEVE VERKOOP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COOP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COOP A RL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COOPERATIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COOPERATIEVE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COOPERATIEVE VENOOTSCHAP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COOPERATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COOPERATIVA AGICOLA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COOPERATIVA LIMITADA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COOPERATIVA PER AZIONI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COORPORATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COPANY ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COPORATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COPR ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COPRORATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COPRPORATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COROPORTION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COROPRATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," COROPROATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORORATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPARATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPERATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPFORATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPOARTION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPOATAION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPOATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPOIRATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPOORATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPOPRATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORAATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORACION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORAION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORAITON ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORARION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORARTION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORATAION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORATE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORATED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORATI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORATIION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORATIN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORATINO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORATINON ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORATIO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORATIOIN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORATIOLN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORATIOM ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORATIOPN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORATITON ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORATOIN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORDATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORQTION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORTAION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORTATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPORTION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPPORATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPRATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPROATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CORPRORATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CROP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CROPORATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CRPORATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," CV ")>0
qui replace asg_corp = 1 if strpos(assignee_std," D ENTERPRISES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," D ENTREPRISE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," D O O ")>0
qui replace asg_corp = 1 if strpos(assignee_std," DíENTREPRISE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," DD ")>0
qui replace asg_corp = 1 if strpos(assignee_std," DEVELOP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," DEVELOPPEMENT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," DEVELOPPEMENTS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," DOING BUSINESS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," DOO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," DORPORATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," EDMS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," EG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ELECTRONIQUE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," EN ZN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," EN ZONEN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ENGINEERING ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ENGINEERS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ENGINES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ENNOBLISSEMENT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ENTERPRISE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ENTRE PRISES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ENTREPOSE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ENTREPRISE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ENTREPRISES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," EQUIP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," EQUIPAMENTOS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," EQUIPEMENT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," EQUIPEMENTS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," EQUIPMENT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," EST ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ESTABILSSEMENTS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ESTABLISHMENT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ESTABLISSEMENT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ESTABLISSEMENTS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ESTABLISSMENTS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ET FILS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ETABLISSEMENT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ETABLISSMENTS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ETS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," FABRIC ")>0
qui replace asg_corp = 1 if strpos(assignee_std," FABRICA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," FABRICATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," FABRICATIONS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," FABRICS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," FABRIEKEN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," FABRIK ")>0
qui replace asg_corp = 1 if strpos(assignee_std," FABRIQUE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," FABRYKA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," FACTORY ")>0
qui replace asg_corp = 1 if strpos(assignee_std," FEDERATED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," FILM ")>0
qui replace asg_corp = 1 if strpos(assignee_std," FINANCIERE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," FIRM ")>0
qui replace asg_corp = 1 if strpos(assignee_std," FIRMA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GBMH ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GBR ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GEBR ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GEBROEDERS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GEBRUEDER ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GENERALE POUR LES TECHNIQUES NOUVELLE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GENOSSENSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GES M B H ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GES MB H ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GES MBH ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GES MHH ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GESELLSCHAFT M B ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GESELLSCHAFT MB H ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GESELLSCHAFT MBH ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GESELLSCHAFT MGH ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GESELLSCHAFT MIT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GESELLSCHAFT MIT BESCHRANKTER ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GESELLSCHAFT MIT BESCHRANKTER HAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GESELLSCHAFTMIT BESCHRANKTER ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GESMBH ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GESSELLSCHAFT MIT BESCHRAENKTER HAUFTUNG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GMBA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GMBB ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GMBG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GMBH ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GMHB ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GNBH ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GORPORATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GROEP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GROUP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GROUPEMENT D ENTREPRISES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," H ")>0
qui replace asg_corp = 1 if strpos(assignee_std," HAFRUNG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," HANDEL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," HANDELABOLAGET ")>0
qui replace asg_corp = 1 if strpos(assignee_std," HANDELEND ONDER ")>0
qui replace asg_corp = 1 if strpos(assignee_std," HANDELORGANISATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," HANDELS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," HANDELSBOLAG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," HANDELSBOLAGET ")>0
qui replace asg_corp = 1 if strpos(assignee_std," HANDELSGESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," HANDESBOLAG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," HATFUNG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," HB ")>0
qui replace asg_corp = 1 if strpos(assignee_std," HF ")>0
qui replace asg_corp = 1 if strpos(assignee_std," HOLDINGS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INC ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INC: ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INCOPORATED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INCORORATED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INCORPARATED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INCORPATED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INCORPORATE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INCORPORATED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INCORPORORATED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INCORPORTED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INCORPOTATED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INCORPRATED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INCORPRORATED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INCROPORATED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INDISTRIES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INDUSRTIES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INDUSTRI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INDUSTRIA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INDUSTRIAL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INDUSTRIAL COP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INDUSTRIALNA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INDUSTRIAS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INDUSTRIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INDUSTRIES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INDUSTRIJA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INDUSTRIJSKO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INGENIEURBUERO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INGENIEURBURO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INGENIEURGESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INGENIEURSBUERO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INGENIEURSBUREAU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INGENIOERSBYRA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INGENJOERSFIRMA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INGENJOERSFIRMAN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INORPORATED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INT L ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INTERNAITONAL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INTERNATIONAL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INTERNATIONAL BUSINESS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INTERNATIONALE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INTERNATIONAUX ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INTERNTIONAL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INTL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INUDSTRIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," INVESTMENT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," IS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," JOINTVENTURE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," K G ")>0
qui replace asg_corp = 1 if strpos(assignee_std," K K ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABAUSHIKI KAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABISHIKI KAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABSUHIKI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABUSHI KIKAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABUSHIBI KAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABUSHIKAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABUSHIKI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABUSHIKKAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABUSHIKU KASISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABUSHKIKI KAISHI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABUSIKI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABUSIKI KAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABUSIKI KAISYA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABUSIKIKAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KAGUSHIKI KAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KAUSHIKI KAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KAISYA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABAUSHIKI GAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABISHIKI GAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABUSHI KIGAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABUSHIBI GAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABUSHIGAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABUSHIKGAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABUSHIKU GASISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABUSHKIKI GAISHI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABUSIKI GAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABUSIKI GAISYA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KABUSIKIGAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KAGUSHIKI GAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KAUSHIKI GAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," GAISYA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KB ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KB KY ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KGAA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KK ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KOM GES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KOMM GES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KOMMANDITBOLAG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KOMMANDITBOLAGET ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KOMMANDITGESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KONSTRUKTIONEN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KOOPERATIVE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KUBUSHIKI KAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," KY ")>0
qui replace asg_corp = 1 if strpos(assignee_std," L ")>0
qui replace asg_corp = 1 if strpos(assignee_std," L C ")>0
qui replace asg_corp = 1 if strpos(assignee_std," L L C ")>0
qui replace asg_corp = 1 if strpos(assignee_std," L P ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LAB ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LABARATOIRE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LABO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LABORATOIRE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LABORATOIRES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LABORATORI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LABORATORIA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LABORATORIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LABORATORIES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LABORATORIET ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LABORATORIUM ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LABORATORY ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LABRATIORIES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LABS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LC ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LCC ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LDA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LDT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LIIMITED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LIMIDADA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LIMINTED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LIMITADA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LIMITADO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LIMITATA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LIMITE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LIMITED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LIMITEE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LIMTED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LINITED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LITD ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LLC ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LLLC ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LLLP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LLP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LMITED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LT EE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LTA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LTC ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LTD ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LTD: ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LTDA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LTDS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LTEE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LTEE; ")>0
qui replace asg_corp = 1 if strpos(assignee_std," LTS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," MAATSCHAPPIJ ")>0
qui replace asg_corp = 1 if strpos(assignee_std," MANUFACTURE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," MANUFACTURE D ARTICLES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," MANUFACTURE DE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," MANUFACTURING ")>0
qui replace asg_corp = 1 if strpos(assignee_std," MARKETING ")>0
qui replace asg_corp = 1 if strpos(assignee_std," MASCHINENBAU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," MASCHINENFABRIK ")>0
qui replace asg_corp = 1 if strpos(assignee_std," MBH ")>0
qui replace asg_corp = 1 if strpos(assignee_std," MBH & CO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," MERCHANDISING ")>0
qui replace asg_corp = 1 if strpos(assignee_std," MET BEPERKTE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," MFG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," N A ")>0
qui replace asg_corp = 1 if strpos(assignee_std," N V ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NAAMLOSE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NAAMLOZE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NAAMLOZE VENNOOTSCAP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NAAMLOZE VENNOOTSHCAP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NAAMLOZEVENNOOTSCHAP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NAUCHNO PRIOZVODSTVENNAYA FIRMA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NAUCHNO PRIOZVODSTVENNOE OBIEDINENIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NAUCHNO PRIOZVODSTVENNY KOOPERATIV ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NAUCHNO PROIZVODSTVENNOE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NAUCHNO PROIZVODSTVENNOE OBJEDINENIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NAUCHNO TEKHNICHESKY KOOPERATIV ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NAUCHNO TEKHNICHESKYKKOOPERATIV ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NAUCHNO TEKHNOLOGICHESKOE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NAUCHNO TEKHNOLOGICHESKOEPREDPRIYATIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NAUCHNOPRIOZVODSTVENNOE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NAUCHNOPROIZVODSTVENNOE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NAUCHNOTEKHNICHESKYKKOOPERATIV ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NAUCHNOTEKNICHESKY ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NV ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NV SA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NV: ")>0
qui replace asg_corp = 1 if strpos(assignee_std," NVSA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OBIDINENIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OBIED ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OBSCHESRYO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OBSCHESTVO & OGRANICHENNOI OTVETSTVENNOSTJU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OBSCHESTVO & ORGANICHENNOI OTVETSTVENNOSTIJU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OBSCHESTVO C ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OBSCHESTVO S ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OBSCHESTVO S OGRANICHENNOI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OBSCHESTVO S OGRANICHENNOI OTVETSTVEN NOSTJU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OBSCHESTVO S OGRANICHENNOI OTVETSTVENNOSTIJU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OBSCHESTVO S OGRANICHENNOI OTVETSTVENNPSTJU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OBSCHESTVO S OGRANICHENNOY OTVETSTVENNOSTJU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OBSCHESTVO S OGRANICHENOI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OBSCHESTVO S ORGANICHENNOI OTVETSTVENNOSTIJU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OBSCHESTVO S ORGANICHENNOI OTVETSTVENNOSTJU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OBSHESTVO S ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OBSHESTVO S OGRANNICHENNOJ ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OBSHESTVO S ORGANICHENNOI OTVETSTVENNOSTIJU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OBSHESTVO S ORGANICHENNOI OTVETSTVENNOSTJU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OCTROOIBUREAU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OGRANICHENNOI OTVETSTVENNOSTIJU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OGRANICHENNOI OTVETSTVENNOSTIJU FIRMA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OGRANICHENNOI OTVETSTVENNOSTJU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OGRANICHENNOY OTVETSTVENNOSTYU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OHG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ONDERNEMING ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OTVETCTVENNOSTJU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OTVETSTVENNOSTIJU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OTVETSTVENNOSTJU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OTVETSTVENNOSTOU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OTVETSTVENNOSTYU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OY ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OYABLTD ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OYG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OYI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OYJ ")>0
qui replace asg_corp = 1 if strpos(assignee_std," OYL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," P ")>0
qui replace asg_corp = 1 if strpos(assignee_std," P C ")>0
qui replace asg_corp = 1 if strpos(assignee_std," P L C ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PARNERSHIP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PARNTERSHIP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PARTNER ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PARTNERS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PARTNERSHIP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PATENT OFFICE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PATENTVERWALTUNGS GESELLSCHAFT MBH ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PATENTVERWALTUNGSGESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PATENTVERWERTUNGSGESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PATNERSHIP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PC ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PER AZIONA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PERSONENVENNOOTSCHAP MET BE PERKTE AANSPRAKELIJKHEID ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PHARM ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PHARMACEUTICA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PHARMACEUTICAL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PHARMACEUTICALS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PHARMACEUTIQUE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PHARMACIA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PHARMACIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PHARMACUETICALS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PLANTS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PLC ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PREDPRIVATIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PREDPRIYATIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PREPRIVATIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PRODUCE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PRODUCT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PRODUCTEURS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PRODUCTION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PRODUCTIONS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PRODUCTIQUE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PRODUCTS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PRODUITS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PRODUKTE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PRODUKTER ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PRODUKTION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PRODUKTIONSGESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PRODUKTUTVECKLING ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PRODURA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PRODUTIS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PROIZVODSTENNOE OBIEDINENIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PROIZVODSTVENNOE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PROIZVODSTVENNOE OBIEDINENIE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PTY ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PTY LIM ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PTYLTD ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PUBLISHING ")>0
qui replace asg_corp = 1 if strpos(assignee_std," PVBA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," RECHERCHES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," RESPONSABILITA LIMITATA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," RESPONSABILITAí LIMITATA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," RESPONSABILITE LIMITE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," RO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," RT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," S A ")>0
qui replace asg_corp = 1 if strpos(assignee_std," S A R L ")>0
qui replace asg_corp = 1 if strpos(assignee_std," S A RL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," S COOP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," S COOP LTDA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," S NC ")>0
qui replace asg_corp = 1 if strpos(assignee_std," S OGRANICHENNOI OTVETSTVENNEST ")>0
qui replace asg_corp = 1 if strpos(assignee_std," S P A ")>0
qui replace asg_corp = 1 if strpos(assignee_std," S PA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," S R L ")>0
qui replace asg_corp = 1 if strpos(assignee_std," S RL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," S S ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SA A RL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SA RL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SA: ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SAAG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SAARL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SALES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SANV ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SARL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SARL: ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SAS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SC ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SCA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SCARL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SCIETE ANONYME ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SCOOP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SCPA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SCRAS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SCRL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SEMPLICE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SERIVICES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SERVICE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SERVICES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SHOP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SIMPLIFIEE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SNC ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOC ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOC ARL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOC COOOP ARL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOC COOP A RESP LIM ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOC COOP A RL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOC COOP R L ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOC COOP RL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOC IND COMM ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOC RL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCCOOP ARL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCCOOPARL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIEDAD ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIEDAD ANONIMA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIEDAD ANONIMYA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIEDAD INDUSTRIAL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIEDAD LIMITADA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIEDADE LIMITADA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIET CIVILE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA A ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA A RESPONSABILITA LIMITATA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA ANONIMA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA CONSORTILE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA CONSORTILE A RESPONSABILITA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA CONSORTILE ARL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA CONSORTILE PER AZION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA CONSORTILE PER AZIONI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA COOPERATIVA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA COOPERATIVA A ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA IN ACCOMANDITA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA IN ACCOMANDITA SEMPLICE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA IN NOME COLLETTIVO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA INDUSTRIA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA PER AXIONI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA PER AZINOI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA PER AZINONI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA PER AZIONI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA PER AZIONI: ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA PER L INDUSTRIA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETA PERAZIONI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETAPERAZIONI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE A ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE A RESPONSABILITE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE A RESPONSABILITE DITE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE A RESPONSABILITEE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE ANANYME ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE ANNOYME ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE ANOMYME ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE ANOMYNE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE ANONVME ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE ANONYM ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE ANONYME ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE ANOYME ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE CHIMIQUE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE CIVILE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE COOPERATIVE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE D APPLICATIONS GENERALES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE D APPLICATIONS MECANIQUES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE D EQUIPEMENT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE D ETUDE ET DE CONSTRUCTION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE D ETUDE ET DE RECHERCHE EN VENTILATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE D ETUDES ET ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE D ETUDES TECHNIQUES ET D ENTREPRISES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE DE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE DE CONSEILS DE RECHERCHES ET D APPLICATIONS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE DE CONSTRUCTIO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE DE FABRICAITON ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE DE FABRICATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE DE PRODUCTION ET DE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE DES TRANSPORTS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE DITE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE DITE : ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE DITE: ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE EN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE EN COMMANDITE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE EN COMMANDITE ENREGISTREE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE EN NOM COLLECTIF ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE ETUDES ET ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE ETUDES ET DEVELOPPEMENTS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE GENERALE POUR LES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE GENERALE POUR LES TECHNIQUES NOVELLES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE METALLURGIQUE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE NOUVELLE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE PAR ACTIONS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE PAR ACTIONS SIMPLIFEE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE PAR ACTIONS SIMPLIFIEE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE TECHNIQUE D APPLICATION ET DE RECHERCHE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETE TECHNIQUE DE PULVERISATION ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETEANONYME ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETEDITE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCIETEINDUSTRIELLE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOCRL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOEHNE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOGRANICHENNOI OTVETSTVENNOSTJU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOHN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SOHNE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SONNER ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SP A ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SP Z OO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SP ZOO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SPA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SPOKAZOO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SPOL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SPOL S R O ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SPOL S RO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SPOL SRO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SPOLECNOST SRO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SPOLKA Z OO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SPOLKA ZOO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SPOLS RO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SPOLSRO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SPRL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SPZ OO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SPZOO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SR ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SR L ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SR1 ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SRI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SRL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SRO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SﬂRL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," SURL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," TEAM ")>0
qui replace asg_corp = 1 if strpos(assignee_std," TECHNIQUES NOUVELLE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," TECHNOLOGIES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," THE FIRM ")>0
qui replace asg_corp = 1 if strpos(assignee_std," TOHO BUSINESS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," TOVARISCHESIVO S OGRANICHENNOI OIVETSIVENNOSTIJU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," TOVARISCHESTVO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," TOVARISCHESTVO S OGRANICHENNOI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," TOVARISCHESTVO S OGRANICHENNOI OTVETSTVENNOSTJU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," TOVARISCHESTVO S OGRANICHENNOI OTVETSVENNOSTJU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," TOVARISCHESTVO S ORGANICHENNOI OTVETSTVENNOSTJU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," TOVARISCHETSTVO S ORGANICHENNOI ")>0
qui replace asg_corp = 1 if strpos(assignee_std," TRADING ")>0
qui replace asg_corp = 1 if strpos(assignee_std," TRADING AS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," TRADING UNDER ")>0
qui replace asg_corp = 1 if strpos(assignee_std," UGINE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," UNTERNEHMEN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," USA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," USINES ")>0
qui replace asg_corp = 1 if strpos(assignee_std," VAKMANSCHAP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," VENNOOTSCHAP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," VENNOOTSCHAP ONDER FIRMA: ")>0
qui replace asg_corp = 1 if strpos(assignee_std," VENNOOTSHAP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," VENNOTSCHAP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," VENOOTSCHAP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," VENTURE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," VERARBEITUNG ")>0
qui replace asg_corp = 1 if strpos(assignee_std," VERKOOP ")>0
qui replace asg_corp = 1 if strpos(assignee_std," VERSICHERUNGSBUERO ")>0
qui replace asg_corp = 1 if strpos(assignee_std," VERTRIEBSGESELLSCHAFT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," VOF ")>0
qui replace asg_corp = 1 if strpos(assignee_std," WERK ")>0
qui replace asg_corp = 1 if strpos(assignee_std," WERKE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," WERKEN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," WERKHUIZEN ")>0
qui replace asg_corp = 1 if strpos(assignee_std," WERKS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," WERKSTAETTE ")>0
qui replace asg_corp = 1 if strpos(assignee_std," WERKSTATT ")>0
qui replace asg_corp = 1 if strpos(assignee_std," WERKZEUGBAU ")>0
qui replace asg_corp = 1 if strpos(assignee_std," WINKEL ")>0
qui replace asg_corp = 1 if strpos(assignee_std," WORKS ")>0
qui replace asg_corp = 1 if strpos(assignee_std," YUGEN KAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," YUGENKAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," YUUGEN KAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," YUUGENKAISHA ")>0
qui replace asg_corp = 1 if strpos(assignee_std," ZOO ")>0


** Government
gen asg_gov=0
qui replace asg_gov = 1 if strpos(assignee_std, " NAT RES COUNCIL ")>0 
qui replace asg_gov = 1 if strpos(assignee_std, " NAT RES INST ")>0 
qui replace asg_gov = 1 if strpos(assignee_std, " NAT SCI COUNCIL ")>0 
qui replace asg_gov = 1 if strpos(assignee_std, " NAT SCI INST ")>0 
qui replace asg_gov = 1 if strpos(assignee_std," AGENCY ")>0
qui replace asg_gov = 1 if strpos(assignee_std," STATE OF ")>0

qui replace asg_gov = 1 if strpos(assignee_std," US ADMIN ")>0
qui replace asg_gov = 1 if strpos(assignee_std," ADMINISTRATOR ")>0
qui replace asg_gov = 1 if strpos(assignee_std," COMMISSIONER OF PATENTS ")>0
qui replace asg_gov = 1 if strpos(assignee_std," US DEPT ")>0
qui replace asg_gov = 1 if strpos(assignee_std," US SEC ")>0

qui replace asg_gov = 1 if strpos(assignee_std, " UK SEC FOR ")>0 
qui replace asg_gov = 1 if strpos(assignee_std, " UK ")>0 & !asg_corp
qui replace asg_gov = 1 if strpos(assignee_std, " COMMONWEALTH ")>0 
qui replace asg_gov = 1 if strpos(assignee_std, " MIN OF ")>0 
qui replace asg_gov = 1 if strpos(assignee_std, " MIN FOR ")>0 

qui replace asg_gov = 1 if strpos(assignee_std, " LETAT FR REPRESENTE ")>0
qui replace asg_gov = 1 if strpos(assignee_std, " LA POSTE ")>0

qui replace asg_gov = 1 if strpos(assignee_std," ADMINISTRATOR ")>0
qui replace asg_gov = 1 if strpos(assignee_std," AGENCE ")>0
qui replace asg_gov = 1 if strpos(assignee_std," AGENCY ")>0
qui replace asg_gov = 1 if strpos(assignee_std," AMMINISTRAZIONE ")>0
qui replace asg_gov = 1 if strpos(assignee_std," AMMINISTRAZIONE ")>0
qui replace asg_gov = 1 if strpos(assignee_std," AUTHORITY ")>0
qui replace asg_gov = 1 if strpos(assignee_std," BOTANICAL GARDEN ")>0
qui replace asg_gov = 1 if strpos(assignee_std," BUNDESANSTALT ")>0
qui replace asg_gov = 1 if strpos(assignee_std," BUNDESREPUBLIK ")>0
qui replace asg_gov = 1 if strpos(assignee_std," CHAMBRE ")>0
qui replace asg_gov = 1 if strpos(assignee_std," CITY ")>0 & !asg_corp
qui replace asg_gov = 1 if strpos(assignee_std," COMISSARIAT ")>0
qui replace asg_gov = 1 if strpos(assignee_std," COMMISARIAT ")>0
qui replace asg_gov = 1 if strpos(assignee_std," COMMISSARAIT ")>0
qui replace asg_gov = 1 if strpos(assignee_std," COMMISSARAT ")>0
qui replace asg_gov = 1 if strpos(assignee_std," COMMISSARIAT ")>0
qui replace asg_gov = 1 if strpos(assignee_std," COMMISSARIET ")>0
qui replace asg_gov = 1 if strpos(assignee_std," COMMISSION ")>0
qui replace asg_gov = 1 if strpos(assignee_std," COMMISSRIAT ")>0
qui replace asg_gov = 1 if strpos(assignee_std," COMMONWEALTH ")>0
qui replace asg_gov = 1 if strpos(assignee_std," COMMUNAUTE ")>0
qui replace asg_gov = 1 if strpos(assignee_std," CONFEDERATED TRIBES ")>0
qui replace asg_gov = 1 if strpos(assignee_std," COOUNCIL OF ")>0
qui replace asg_gov = 1 if strpos(assignee_std," COUCIL OF ")>0
qui replace asg_gov = 1 if strpos(assignee_std," COUNCIL ")>0
qui replace asg_gov = 1 if strpos(assignee_std," COUNSEL OF ")>0
qui replace asg_gov = 1 if strpos(assignee_std," COUNTY ")>0
qui replace asg_gov = 1 if strpos(assignee_std," DEN PRAESIDENTEN ")>0
qui replace asg_gov = 1 if strpos(assignee_std," DEPARTMENT OF AGRICULTURE ")>0
qui replace asg_gov = 1 if strpos(assignee_std," DETAT ")>0
qui replace asg_gov = 1 if strpos(assignee_std," ETAT ")>0
qui replace asg_gov = 1 if strpos(assignee_std," GERMANY ")>0 & !asg_corp
qui replace asg_gov = 1 if strpos(assignee_std," GEZONDHEIDSDIENST ")>0
qui replace asg_gov = 1 if strpos(assignee_std," GOUVERNEMENT ")>0
qui replace asg_gov = 1 if strpos(assignee_std," GOUVERNMENT ")>0
qui replace asg_gov = 1 if strpos(assignee_std," GOVERNER ")>0
qui replace asg_gov = 1 if strpos(assignee_std," GOVERNMENT ")>0
qui replace asg_gov = 1 if strpos(assignee_std," GOVERNOR ")>0
qui replace asg_gov = 1 if strpos(assignee_std," HER MAJESTY ")>0
qui replace asg_gov = 1 if strpos(assignee_std," KEN ")>0
qui replace asg_gov = 1 if strpos(assignee_std," LETAT ")>0
qui replace asg_gov = 1 if strpos(assignee_std," MINISTER ")>0
qui replace asg_gov = 1 if strpos(assignee_std," MINISTERO ")>0
qui replace asg_gov = 1 if strpos(assignee_std," MINISTRE ")>0
qui replace asg_gov = 1 if strpos(assignee_std," MINISTRI ")>0
qui replace asg_gov = 1 if strpos(assignee_std," MINISTRO ")>0
qui replace asg_gov = 1 if strpos(assignee_std," MINISTRY ")>0
qui replace asg_gov = 1 if strpos(assignee_std," MUNICIPAL UTILITY DISTRICT ")>0
qui replace asg_gov = 1 if strpos(assignee_std," NACIONAL ")>0
qui replace asg_gov = 1 if strpos(assignee_std," NATIONAL ")>0 & !asg_corp
qui replace asg_gov = 1 if strpos(assignee_std," NAZIONALE ")>0
qui replace asg_gov = 1 if strpos(assignee_std," POLICE ")>0
qui replace asg_gov = 1 if strpos(assignee_std," PREFECTURE ")>0
qui replace asg_gov = 1 if strpos(assignee_std," PRESIDENZA DEL CONSIGLIO DEI MINISTRI ")>0
qui replace asg_gov = 1 if strpos(assignee_std," PRESIDENZADEL CONSIGLIO DEL MINISTRI ")>0
qui replace asg_gov = 1 if strpos(assignee_std," REPUBLIC ")>0
qui replace asg_gov = 1 if strpos(assignee_std," RESEARCH COUNCIL ")>0
qui replace asg_gov = 1 if strpos(assignee_std," SECRETARIAT ")>0
qui replace asg_gov = 1 if strpos(assignee_std," SECRETARY ")>0
qui replace asg_gov = 1 if strpos(assignee_std," STAAT ")>0
qui replace asg_gov = 1 if strpos(assignee_std," STADT ")>0
qui replace asg_gov = 1 if strpos(assignee_std," STATE ")>0 & !asg_corp
qui replace asg_gov = 1 if strpos(assignee_std," STATO ")>0
qui replace asg_gov = 1 if strpos(assignee_std," THE QUEEN ")>0
qui replace asg_gov = 1 if strpos(assignee_std," VILLE ")>0 

** clean up government departments
qui replace assignee_std = subinstr(assignee_std," SEC OF DEPT OF "," DEPT OF ",1)
qui replace assignee_std = subinstr(assignee_std," SEC OF THE DEPT OF "," DEPT OF ",1)
qui replace asg_gov = 1 if strpos(assignee_std," CNRS ")>0
qui replace asg_gov = 1 if strpos(assignee_std," CENT NAT DE LA RECH ")>0
qui replace asg_gov = 1 if strpos(assignee_std," CENT NAT DETUDES SPATIALES ")>0
qui replace asg_gov = 1 if strpos(assignee_std, " DESY ")>0 

** universities
gen asg_univ=0
qui replace asg_univ = 1 if strpos(assignee_std," ACADEM")>0
qui replace asg_univ = 1 if strpos(assignee_std," ACAD ")>0
qui replace asg_univ = 1 if strpos(assignee_std," AKAD ")>0
qui replace asg_univ = 1 if strpos(assignee_std," COLLEGE ")>0
qui replace asg_univ = 1 if strpos(assignee_std," CURATORS ")>0
qui replace asg_univ = 1 if strpos(assignee_std," ECOLE ")>0
qui replace asg_univ = 1 if strpos(assignee_std," FACULTE ")>0
qui replace asg_univ = 1 if strpos(assignee_std," INST OF TECH ")>0
qui replace asg_univ = 1 if strpos(assignee_std," INST OF TECH")>0
qui replace asg_univ = 1 if strpos(assignee_std," INSTITUTE OF TECHNOLOGY ")>0
qui replace asg_univ = 1 if strpos(assignee_std," INTERNUIVERSITAIR ")>0
qui replace asg_univ = 1 if strpos(assignee_std," INTERUNIVERITAIR ")>0
qui replace asg_univ = 1 if strpos(assignee_std," POLITEC ")>0
qui replace asg_univ = 1 if strpos(assignee_std," POLYTEC ")>0
qui replace asg_univ = 1 if strpos(assignee_std," REGENTS ")>0
qui replace asg_univ = 1 if strpos(assignee_std," RIJKSUNIVERSTTEIT ")>0
qui replace asg_univ = 1 if strpos(assignee_std," SCHOOL ")>0
qui replace asg_univ = 1 if strpos(assignee_std," SCHULE ")>0
qui replace asg_univ = 1 if strpos(assignee_std," SUPERVISORS ")>0
qui replace asg_univ = 1 if strpos(assignee_std," TRUSTEES ")>0
qui replace asg_univ = 1 if strpos(assignee_std," UMIVERSIDAD ")>0
qui replace asg_univ = 1 if strpos(assignee_std," UNIV ")>0
qui replace asg_univ = 1 if strpos(assignee_std," UNIVERISITY ")>0
qui replace asg_univ = 1 if strpos(assignee_std," UNIVERISTY ")>0
qui replace asg_univ = 1 if strpos(assignee_std," UNIVERSATIES ")>0
qui replace asg_univ = 1 if strpos(assignee_std," UNIVERSI")>0
qui replace asg_univ = 1 if strpos(assignee_std," UNIVERSTIA ")>0
qui replace asg_univ = 1 if strpos(assignee_std," UNIVERSTITAT ")>0
qui replace asg_univ = 1 if strpos(assignee_std," UNIVERSTITAET ")>0
qui replace asg_univ = 1 if strpos(assignee_std," UNIVERSTITY ")>0
qui replace asg_univ = 1 if strpos(assignee_std," UNIVERSTIY ")>0
qui replace asg_univ = 1 if strpos(assignee_std," UNIVERSY ")>0
qui replace asg_univ = 1 if strpos(assignee_std," UNIVERZ ")>0
qui replace asg_univ = 1 if strpos(assignee_std," UNVERSITY ")>0
qui replace asg_univ = 1 if strpos(assignee_std," KU LEUVEN ")>0

** Non-profit institutes
gen asg_institute=0
qui replace asg_institute = 1 if strpos(assignee_std," RESEARCH COUNCIL ")!=0
qui replace asg_institute = 1 if strpos(assignee_std," RES COUNCIL ")!=0
qui replace asg_institute = 1 if strpos(assignee_std, " FRAUNHOFER GES ")>0 
qui replace asg_institute = 1 if strpos(assignee_std, " MAX PLANCK GES ")>0 
qui replace asg_institute = 1 if strpos(assignee_std," COUNCIL OF ")>0 & strpos(assignee_std," RES ")>0
qui replace asg_institute = 1 if strpos(assignee_std," ASBL ")>0
qui replace asg_institute = 1 if strpos(assignee_std," ASOCIACION ")>0
*qui replace asg_institute = 1 if strpos(assignee_std," ASSOC ")>0
qui replace asg_institute = 1 if strpos(assignee_std," ASSOCIATION ")>0 & strpos(assignee_std," AUTOMOBILE ASSOCIATION ")==0
qui replace asg_institute = 1 if strpos(assignee_std," ASSOCIAZIONE ")>0
qui replace asg_institute = 1 if strpos(assignee_std," BLOOD ")>0
qui replace asg_institute = 1 if strpos(assignee_std," BLOOD CENTER ")>0
qui replace asg_institute = 1 if strpos(assignee_std," BLOOD SERVICES ")>0
qui replace asg_institute = 1 if strpos(assignee_std," BLOOD TRANSFUSION SERVICE ")>0
qui replace asg_institute = 1 if strpos(assignee_std," CHURCH ")>0 & strpos(assignee_std," CHURCH & DWIGHT ")==0
qui replace asg_institute = 1 if strpos(assignee_std," COOPERATIVE ")>0
qui replace asg_institute = 1 if strpos(assignee_std," E V ")>0
qui replace asg_institute = 1 if strpos(assignee_std," EV ")>0
qui replace asg_institute = 1 if strpos(assignee_std," FEDERATION ")>0
qui replace asg_institute = 1 if strpos(assignee_std," FONDATION ")>0
qui replace asg_institute = 1 if strpos(assignee_std," FONDATIONE ")>0
qui replace asg_institute = 1 if strpos(assignee_std," FOUNDATION ")>0
qui replace asg_institute = 1 if strpos(assignee_std," FOUND ")>0 & asg_univ == 0
qui replace asg_institute = 1 if strpos(assignee_std," FORSKNINGSINSTITUT ")>0
qui replace asg_institute = 1 if strpos(assignee_std," FUNDACAO ")>0
qui replace asg_institute = 1 if strpos(assignee_std," FUNDACIO ")>0
qui replace asg_institute = 1 if strpos(assignee_std," FUNDACION ")>0
qui replace asg_institute = 1 if strpos(assignee_std," FUNDATION ")>0
qui replace asg_institute = 1 if strpos(assignee_std," INDUSTRIAL TECHNOLOGY RESEARCH ")>0
qui replace asg_institute = 1 if strpos(assignee_std," INSITUT ")>0
qui replace asg_institute = 1 if strpos(assignee_std," INSITUTE ")>0
qui replace asg_institute = 1 if strpos(assignee_std," INST ")>0 & asg_univ == 0
qui replace asg_institute = 1 if strpos(assignee_std," INSTIT ")>0 & asg_univ == 0
qui replace asg_institute = 1 if strpos(assignee_std," INSTITUTE ")>0 & asg_univ == 0 & strpos(assignee_std," GENETICS ")==0
qui replace asg_institute = 1 if strpos(assignee_std," INSTYTUT ")>0
qui replace asg_institute = 1 if strpos(assignee_std," INSTYTUT ")>0
qui replace asg_institute = 1 if strpos(assignee_std," INTITUTE ")>0
qui replace asg_institute = 1 if strpos(assignee_std," ISTITUTO ")>0
qui replace asg_institute = 1 if strpos(assignee_std," KENKYUSHO ")>0
qui replace asg_institute = 1 if strpos(assignee_std," MINISTRIES ")>0
qui replace asg_institute = 1 if strpos(assignee_std," SOCIETY ")>0
qui replace asg_institute = 1 if strpos(assignee_std," STICHTING ")>0
qui replace asg_institute = 1 if strpos(assignee_std," STIFTELSE ")>0
qui replace asg_institute = 1 if strpos(assignee_std," STIFTUNG ")>0
qui replace asg_institute = 1 if strpos(assignee_std," TRANSFUSION ")>0
qui replace asg_institute = 1 if strpos(assignee_std," TRANSFUSION SANGUINE ")>0
qui replace asg_institute = 1 if strpos(assignee_std," TRUST ")>0
qui replace asg_institute = 1 if strpos(assignee_std," VERENINING ")>0
qui replace asg_institute = 1 if strpos(assignee_std," VZW ")>0


********************************************************************************
* Hospitals 
********************************************************************************
gen asg_hospital=0
qui replace asg_hospital = 1 if strpos(assignee_std," AMTS SYGEHUS ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," AMTSSYGEHUS ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," BOLNHITSA ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," BOLNISN ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," BOLNITSA ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," BOLNYITSA ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," CENTRE ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," CLINIC ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," CLINICA ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," CLINIQUE ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," HAIGLA ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," HOPITAL ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," HOPITAUX ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," HOPSITAL ")>0 
qui replace asg_hospital = 1 if strpos(assignee_std," HOSITAL ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," HOSP ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," HOSPIDAL ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," HOSPITAL ")>0 & (strpos(assignee_std," HOSPITAL PRODUCTS ")==0 & strpos(assignee_std," HOSPITAL SUPPLY ")==0)
qui replace asg_hospital = 1 if strpos(assignee_std," HOSPITALARIO ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," HOSPITALET ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," HOSPITAUX ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," KESKUSSAIRAALA ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," KLIINIK ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," KLINIK ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," KLINIKA ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," KLINIKKA ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," KLINIKUM ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," KORHAZ ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," KRANKENHAUS ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," LHOSPTALET ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," LIGONINE ")>0
*qui replace asg_hospital = 1 if strpos(assignee_std," MEDICAL ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," MEDICAL CENTER ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," NEMOCNICA ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," NEMOCNICE ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," NOSOCOMIO ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," NOSOKOMIO ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," OSPEDALE ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," OSPETALE ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," OSPITALIERI ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," POLICLINICA ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," POLICLINICO ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," POLIKLINIK ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," SAIRAALA ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," SJUKHUS ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," SJUKHUSET ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," SLIMNICA ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," SPITAL ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," STACIONARS ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," STANICA ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," STREDISKO ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," SYGEHUS ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," SYGEHUSET ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," SYKEHUS ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," SZPITAL ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," UNIVERSITAETSKLINIK ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," ZIEKENHUIS ")>0
qui replace asg_hospital = 1 if strpos(assignee_std," CITY OF HOPE ")>0

* 



