/// PROJECT: Spillover Effects 
/// GOAL: Link patent data - NETS
/// AUTHOR: Theresa Bührle
/// CREATION: 14-11-2023
/// LAST UPDATE: 15-11-2023

/*
ssc install matchit
ssc install freqindex
*/

cd "D:\DOCS\3_Forschung\Topics\Spillover migration\2_Empirical\2_1_Data\"

use "_matching\Patent Daten\assignee_clean.dta", clear

gen standard_name_patent=" "+upper(organization)+" "

foreach var of varlist standard_name_patent  {

replace `var' = subinstr(`var', ".", "", .)
replace `var' = subinstr(`var', ",", "", .)
replace `var' = subinstr(`var', "-", "", .)
replace `var' = subinstr(`var', "(", "", .)
replace `var' = subinstr(`var', ")", "", .)
replace `var' = subinstr(`var', "/", "", .)

** clean names that end in (THE) or start with THE
replace `var'=substr(`var', 5, .) if substr(`var', 1, 5)==" THE "
replace `var'=substr(`var', 1, length(`var')-6) if substr(`var', -6, 6)=="(THE) "
replace `var'=substr(`var', 1, length(`var')-5) if substr(`var', -5, 5)=="-OLD "

** Recode all common words for "AND" to &
replace `var' = subinstr(`var', " AND ", " & ", .) if substr(`var',1,5)!=" AND "
replace `var' = subinstr(`var', " & AND ", " & ", .) 
replace `var' = subinstr(`var', " ET ", " & ", .) if substr(`var',1,4)!=" ET "
replace `var' = subinstr(`var', " & ET ", " & ", .)
replace `var' = subinstr(`var', " UND ", " & ", .) if substr(`var',1,5)!=" UND "
replace `var' = subinstr(`var', "+", "&", .)
replace `var' = itrim(`var')

replace `var' = subinstr( `var'," A B "," AB ",1)
replace `var' = subinstr( `var'," A CALIFORNIA CORP "," CORP ",1)
replace `var' = subinstr( `var'," A DELAWARE CORP "," CORP ",1)
replace `var' = subinstr( `var'," AKTIEBOLAGET "," AB ",1)
replace `var' = subinstr( `var'," AKTIEBOLAG "," AB ",1)
replace `var' = subinstr( `var'," ACADEMY "," ACAD ",1)
replace `var' = subinstr( `var'," ACTIEN GESELLSCHAFT "," AG ",1)
replace `var' = subinstr( `var'," ACTIENGESELLSCHAFT "," AG ",1)
replace `var' = subinstr( `var'," AKTIEN GESELLSCHAFT "," AG ",1)
replace `var' = subinstr( `var'," AKTIENGESELLSCHAFT "," AG ",1)
replace `var' = subinstr( `var'," AGRICOLAS "," AGRIC ",1)
replace `var' = subinstr( `var'," AGRICOLA "," AGRIC ",1)
replace `var' = subinstr( `var'," AGRICOLES "," AGRIC ",1)
replace `var' = subinstr( `var'," AGRICOLE "," AGRIC ",1)
replace `var' = subinstr( `var'," AGRICOLI "," AGRIC ",1)
replace `var' = subinstr( `var'," AGRICOLTURE "," AGRIC ",1)
replace `var' = subinstr( `var'," AGRICULTURA "," AGRIC ",1)
replace `var' = subinstr( `var'," AGRICULTURAL "," AGRIC ",1)
replace `var' = subinstr( `var'," AGRICULTURE "," AGRIC ",1)
replace `var' = subinstr( `var'," AKADEMIA "," AKAD ",1)
replace `var' = subinstr( `var'," AKADEMIEI "," AKAD ",1)
replace `var' = subinstr( `var'," AKADEMIE "," AKAD ",1)
replace `var' = subinstr( `var'," AKADEMII "," AKAD ",1)
replace `var' = subinstr( `var'," AKADEMIJA "," AKAD ",1)
replace `var' = subinstr( `var'," AKADEMIYA "," AKAD ",1)
replace `var' = subinstr( `var'," AKADEMIYAKH "," AKAD ",1)
replace `var' = subinstr( `var'," AKADEMIYAM "," AKAD ",1)
replace `var' = subinstr( `var'," AKADEMIYAMI "," AKAD ",1)
replace `var' = subinstr( `var'," AKADEMIYU "," AKAD ",1)
replace `var' = subinstr( `var'," AKADEMI "," AKAD ",1)
replace `var' = subinstr( `var'," ALLGEMEINER "," ALLG ",1)
replace `var' = subinstr( `var'," ALLGEMEINE "," ALLG ",1)
replace `var' = subinstr( `var'," ANTREPRIZA "," ANTR ",1)
replace `var' = subinstr( `var'," APARARII "," APAR ",1)
replace `var' = subinstr( `var'," APARATELOR "," APAR ",1)
replace `var' = subinstr( `var'," APPARATEBAU "," APP ",1)
replace `var' = subinstr( `var'," APPARATUS "," APP ",1)
replace `var' = subinstr( `var'," APPARECHHI "," APP ",1)
replace `var' = subinstr( `var'," APPAREILLAGES "," APP ",1)
replace `var' = subinstr( `var'," APPAREILLAGE "," APP ",1)
replace `var' = subinstr( `var'," APPAREILS "," APP ",1)
replace `var' = subinstr( `var'," APPAREIL "," APP ",1)
replace `var' = subinstr( `var'," APARATE "," APAR ",1)
replace `var' = subinstr( `var'," APPARATE "," APP ",1)
replace `var' = subinstr( `var'," APPLICATIONS "," APPL ",1)
replace `var' = subinstr( `var'," APPLICATION "," APPL ",1)
replace `var' = subinstr( `var'," APPLICAZIONE "," APPL ",1)
replace `var' = subinstr( `var'," APPLICAZIONI "," APPL ",1)
replace `var' = subinstr( `var'," ANPARTSSELSKABET "," APS ",1)
replace `var' = subinstr( `var'," ANPARTSSELSKAB "," APS ",1)
replace `var' = subinstr( `var'," A/S "," AS ",1)
replace `var' = subinstr( `var'," AKTIESELSKABET "," AS ",1)
replace `var' = subinstr( `var'," AKTIESELSKAB "," AS ",1)
replace `var' = subinstr( `var'," ASSOCIACAO "," ASSOC ",1)
replace `var' = subinstr( `var'," ASSOCIATED "," ASSOC ",1)
replace `var' = subinstr( `var'," ASSOCIATES "," ASSOCIATES ",1)
replace `var' = subinstr( `var'," ASSOCIATE "," ASSOCIATES ",1)
replace `var' = subinstr( `var'," ASSOCIATION "," ASSOC ",1)
replace `var' = subinstr( `var'," BETEILIGUNGSGESELLSCHAFT MBH "," BET GMBH ",1)
replace `var' = subinstr( `var'," BETEILIGUNGS GESELLSCHAFT MIT "," BET GMBH ",1)
replace `var' = subinstr( `var'," BETEILIGUNGSGESELLSCHAFT "," BET GES ",1)
replace `var' = subinstr( `var'," BESCHRANKTER HAFTUNG "," BET GMBH ",1)
replace `var' = subinstr( `var'," BROEDERNA "," BRDR ",1)
replace `var' = subinstr( `var'," BROEDRENE "," BRDR ",1)
replace `var' = subinstr( `var'," BRODERNA "," BRDR ",1)
replace `var' = subinstr( `var'," BRODRENE "," BRDR ",1)
replace `var' = subinstr( `var'," BROTHERS "," BROS ",1)
replace `var' = subinstr( `var'," BESLOTEN VENNOOTSCHAP MET "," BV ",1)
replace `var' = subinstr( `var'," BESLOTEN VENNOOTSCHAP "," BV ",1)
replace `var' = subinstr( `var'," BEPERKTE AANSPRAKELIJKHEID "," BV ",1)
replace `var' = subinstr( `var'," CLOSE CORPORATION "," CC ",1)
replace `var' = subinstr( `var'," CENTER "," CENT ",1)
replace `var' = subinstr( `var'," CENTRAAL "," CENT ",1)
replace `var' = subinstr( `var'," CENTRALA "," CENT ",1)
replace `var' = subinstr( `var'," CENTRALES "," CENT ",1)
replace `var' = subinstr( `var'," CENTRALE "," CENT ",1)
replace `var' = subinstr( `var'," CENTRAL "," CENT ",1)
replace `var' = subinstr( `var'," CENTRAUX "," CENT ",1)
replace `var' = subinstr( `var'," CENTRE "," CENT ",1)
replace `var' = subinstr( `var'," CENTRO "," CENT ",1)
replace `var' = subinstr( `var'," CENTRUL "," CENT ",1)
replace `var' = subinstr( `var'," CENTRUM "," CENT ",1)
replace `var' = subinstr( `var'," CERCETARE "," CERC ",1)
replace `var' = subinstr( `var'," CERCETARI "," CERC ",1)
replace `var' = subinstr( `var'," CHEMICALS "," CHEM ",1)
replace `var' = subinstr( `var'," CHEMICAL "," CHEM ",1)
replace `var' = subinstr( `var'," CHEMICKEJ "," CHEM ",1)
replace `var' = subinstr( `var'," CHEMICKE "," CHEM ",1)
replace `var' = subinstr( `var'," CHEMICKYCH "," CHEM ",1)
replace `var' = subinstr( `var'," CHEMICKY "," CHEM ",1)
replace `var' = subinstr( `var'," CHEMICZNE "," CHEM ",1)
replace `var' = subinstr( `var'," CHEMICZNY "," CHEM ",1)
replace `var' = subinstr( `var'," CHEMIE "," CHEM ",1)
replace `var' = subinstr( `var'," CHEMII "," CHEM ",1)
replace `var' = subinstr( `var'," CHEMISCHE "," CHEM ",1)
replace `var' = subinstr( `var'," CHEMISCH "," CHEM ",1)
replace `var' = subinstr( `var'," CHEMISKEJ "," CHEM ",1)
replace `var' = subinstr( `var'," CHEMISTRY "," CHEM ",1)
replace `var' = subinstr( `var'," CHIMICA "," CHIM ",1)
replace `var' = subinstr( `var'," CHIMICE "," CHIM ",1)
replace `var' = subinstr( `var'," CHIMICI "," CHIM ",1)
replace `var' = subinstr( `var'," CHIMICO "," CHIM ",1)
replace `var' = subinstr( `var'," CHIMIC "," CHIM ",1)
replace `var' = subinstr( `var'," CHIMIEI "," CHIM ",1)
replace `var' = subinstr( `var'," CHIMIE "," CHIM ",1)
replace `var' = subinstr( `var'," CHIMIESKOJ "," CHIM ",1)
replace `var' = subinstr( `var'," CHIMII "," CHIM ",1)
replace `var' = subinstr( `var'," CHIMIKO "," CHIM ",1)
replace `var' = subinstr( `var'," CHIMIQUES "," CHIM ",1)
replace `var' = subinstr( `var'," CHIMIQUE "," CHIM ",1)
replace `var' = subinstr( `var'," CHIMIYAKH "," CHIM ",1)
replace `var' = subinstr( `var'," CHIMIYAMI "," CHIM ",1)
replace `var' = subinstr( `var'," CHIMIYAM "," CHIM ",1)
replace `var' = subinstr( `var'," CHIMIYA "," CHIM ",1)
replace `var' = subinstr( `var'," CHIMIYU "," CHIM ",1)
replace `var' = subinstr( `var'," COMPAGNIE FRANCAISE "," CIE FR ",1)
replace `var' = subinstr( `var'," COMPAGNIE GENERALE "," CIE GEN ",1)
replace `var' = subinstr( `var'," COMPAGNIE INDUSTRIALE "," CIE IND ",1)
replace `var' = subinstr( `var'," COMPAGNIE INDUSTRIELLE "," CIE IND ",1)
replace `var' = subinstr( `var'," COMPAGNIE INDUSTRIELLES "," CIE IND ",1)
replace `var' = subinstr( `var'," COMPAGNIE INTERNATIONALE "," CIE INT ",1)
replace `var' = subinstr( `var'," COMPAGNIE NATIONALE "," CIE NAT ",1)
replace `var' = subinstr( `var'," COMPAGNIE PARISIENNE "," CIE PARIS ",1)
replace `var' = subinstr( `var'," COMPAGNIE PARISIENN "," CIE PARIS ",1)
replace `var' = subinstr( `var'," COMPAGNIE PARISIEN "," CIE PARIS ",1)
replace `var' = subinstr( `var'," COMPANIES "," CO ",1)
replace `var' = subinstr( `var'," COMPAGNIA "," CIA ",1)
replace `var' = subinstr( `var'," COMPANHIA "," CIA ",1)
replace `var' = subinstr( `var'," COMPAGNIE "," CIE ",1)
replace `var' = subinstr( `var'," COMPANY "," CO ",1)
replace `var' = subinstr( `var'," COMBINATUL "," COMB ",1)
replace `var' = subinstr( `var'," COMMERCIALE "," COMML ",1)
replace `var' = subinstr( `var'," COMMERCIAL "," COMML ",1)
replace `var' = subinstr( `var'," CONSOLIDATED "," CONSOL ",1)
replace `var' = subinstr( `var'," CONSTRUCCIONES "," CONSTR ",1)
replace `var' = subinstr( `var'," CONSTRUCCIONE "," CONSTR ",1) 
replace `var' = subinstr( `var'," CONSTRUCCION "," CONSTR ",1)
replace `var' = subinstr( `var'," CONSTRUCTIE "," CONSTR ",1)
replace `var' = subinstr( `var'," CONSTRUCTII "," CONSTR ",1)
replace `var' = subinstr( `var'," CONSTRUCTIILOR "," CONSTR ",1)
replace `var' = subinstr( `var'," CONSTRUCTIONS "," CONSTR ",1)
replace `var' = subinstr( `var'," CONSTRUCTION "," CONSTR ",1)
replace `var' = subinstr( `var'," CONSTRUCTORTUL "," CONSTR ",1)
replace `var' = subinstr( `var'," CONSTRUCTORUL "," CONSTR ",1)
replace `var' = subinstr( `var'," CONSTRUCTOR "," CONSTR ",1)
replace `var' = subinstr( `var'," CO OPERATIVES "," COOP ",1)
replace `var' = subinstr( `var'," CO OPERATIVE "," COOP ",1)
replace `var' = subinstr( `var'," COOPERATIEVE "," COOP ",1)
replace `var' = subinstr( `var'," COOPERATIVA "," COOP ",1)
replace `var' = subinstr( `var'," COOPERATIVES "," COOP ",1)
replace `var' = subinstr( `var'," COOPERATIVE "," COOP ",1)
replace `var' = subinstr( `var'," INCORPORATED "," INC ",1)  
replace `var' = subinstr( `var'," INCORPORATION "," INC ",1)
replace `var' = subinstr( `var'," CORPORATE "," CORP ",1)
replace `var' = subinstr( `var'," CORPORATION OF AMERICA "," CORP ",1)
replace `var' = subinstr( `var'," CORPORATION "," CORP ",1)
replace `var' = subinstr( `var'," CORPORASTION "," CORP ",1)
replace `var' = subinstr( `var'," CORPORATIOON "," CORP ",1)
replace `var' = subinstr( `var'," COSTRUZIONI "," COSTR ",1)
replace `var' = subinstr( `var'," DEUTSCHEN "," DDR ",1)
replace `var' = subinstr( `var'," DEUTSCHE "," DDR ",1)
replace `var' = subinstr( `var'," DEMOKRATISCHEN REPUBLIK "," DDR ",1)
replace `var' = subinstr( `var'," DEMOKRATISCHE REPUBLIK "," DDR ",1)
replace `var' = subinstr( `var'," DEPARTEMENT "," DEPT ",1)
replace `var' = subinstr( `var'," DEPARTMENT "," DEPT ",1)
replace `var' = subinstr( `var'," DEUTSCHES "," DEUT ",1)
replace `var' = subinstr( `var'," DEUTSCHEN "," DEUT ",1)
replace `var' = subinstr( `var'," DEUTSCHER "," DEUT ",1)
replace `var' = subinstr( `var'," DEUTSCHLAND "," DEUT ",1)
replace `var' = subinstr( `var'," DEUTSCHE "," DEUT ",1)
replace `var' = subinstr( `var'," DEUTSCH "," DEUT ",1)
replace `var' = subinstr( `var'," DEVELOPMENTS "," DEV ",1)
replace `var' = subinstr( `var'," DEVELOPMENT "," DEV ",1)
replace `var' = subinstr( `var'," DEVELOPPEMENTS "," DEV ",1)
replace `var' = subinstr( `var'," DEVELOPPEMENT "," DEV ",1)
replace `var' = subinstr( `var'," DEVELOP "," DEV ",1)
replace `var' = subinstr( `var'," DIVISIONE "," DIV ",1)
replace `var' = subinstr( `var'," DIVISION "," DIV ",1)
replace `var' = subinstr( `var'," ENGINEERING "," ENG ",1)
replace `var' = subinstr( `var'," EQUIPEMENTS "," EQUIP ",1)
replace `var' = subinstr( `var'," EQUIPEMENT "," EQUIP ",1)
replace `var' = subinstr( `var'," EQUIPMENTS "," EQUIP ",1)
replace `var' = subinstr( `var'," EQUIPMENT "," EQUIP ",1)
replace `var' = subinstr( `var'," ESTABLISHMENTS "," ESTAB ",1)
replace `var' = subinstr( `var'," ESTABLISHMENT "," ESTAB ",1)
replace `var' = subinstr( `var'," ESTABLISSEMENTS "," ESTAB ",1)
replace `var' = subinstr( `var'," ESTABLISSEMENT "," ESTAB ",1)
replace `var' = subinstr( `var'," ETABLISSEMENTS "," ETAB ",1)
replace `var' = subinstr( `var'," ETABLISSEMENT "," ETAB ",1)
replace `var' = subinstr( `var'," ETABS "," ETAB ",1)
replace `var' = subinstr( `var'," ETS "," ETAB ",1)
replace `var' = subinstr( `var'," ETUDES "," ETUD ",1)
replace `var' = subinstr( `var'," ETUDE "," ETUD ",1)
replace `var' = subinstr( `var'," EUROPAEISCHEN "," EURO ",1)
replace `var' = subinstr( `var'," EUROPAEISCHES "," EURO ",1)
replace `var' = subinstr( `var'," EUROPAEISCHE "," EURO ",1)
replace `var' = subinstr( `var'," EUROPAISCHEN "," EURO ",1)
replace `var' = subinstr( `var'," EUROPAISCHES "," EURO ",1)
replace `var' = subinstr( `var'," EUROPAISCHE "," EURO ",1)
replace `var' = subinstr( `var'," EUROPEAN "," EURO ",1)
replace `var' = subinstr( `var'," EUROPEENNE "," EURO ",1)
replace `var' = subinstr( `var'," EUROPEEN "," EURO ",1)
replace `var' = subinstr( `var'," EUROPEA "," EURO ",1)
replace `var' = subinstr( `var'," EUROPE "," EURO ",1)
replace `var' = subinstr( `var'," EINGETRAGENER VEREIN "," EV ",1)
replace `var' = subinstr( `var'," EXPLOATERINGS "," EXPL ",1)
replace `var' = subinstr( `var'," EXPLOATERING "," EXPL ",1)
replace `var' = subinstr( `var'," EXPLOITATIE "," EXPL ",1)
replace `var' = subinstr( `var'," EXPLOITATIONS "," EXPL ",1)
replace `var' = subinstr( `var'," EXPLOITATION "," EXPL ",1)
replace `var' = subinstr( `var'," FIRMA "," FA ",1)
replace `var' = subinstr( `var'," FABBRICAZIONI "," FAB ",1)
replace `var' = subinstr( `var'," FABBRICHE "," FAB ",1)
replace `var' = subinstr( `var'," FABRICATIONS "," FAB ",1)
replace `var' = subinstr( `var'," FABRICATION "," FAB ",1)
replace `var' = subinstr( `var'," FABBRICA "," FAB ",1)
replace `var' = subinstr( `var'," FABRICA "," FAB ",1)
replace `var' = subinstr( `var'," FABRIEKEN "," FAB ",1)
replace `var' = subinstr( `var'," FABRIEK "," FAB ",1)
replace `var' = subinstr( `var'," FABRIKER "," FAB ",1)
replace `var' = subinstr( `var'," FABRIK "," FAB ",1)
replace `var' = subinstr( `var'," FABRIQUES "," FAB ",1)
replace `var' = subinstr( `var'," FABRIQUE "," FAB ",1)
replace `var' = subinstr( `var'," FABRIZIO "," FAB ",1)
replace `var' = subinstr( `var'," FABRYKA "," FAB ",1)
replace `var' = subinstr( `var'," FARMACEUTICA "," FARM ",1)
replace `var' = subinstr( `var'," FARMACEUTICE "," FARM ",1)
replace `var' = subinstr( `var'," FARMACEUTICHE "," FARM ",1)
replace `var' = subinstr( `var'," FARMACEUTICI "," FARM ",1)
replace `var' = subinstr( `var'," FARMACEUTICOS "," FARM ",1)
replace `var' = subinstr( `var'," FARMACEUTICO "," FARM ",1)
replace `var' = subinstr( `var'," FARMACEUTISK "," FARM ",1)
replace `var' = subinstr( `var'," FARMACEVTSKIH "," FARM ",1)
replace `var' = subinstr( `var'," FARMACIE "," FARM ",1)
replace `var' = subinstr( `var'," FONDATION "," FOND ",1)
replace `var' = subinstr( `var'," FONDAZIONE "," FOND ",1)
replace `var' = subinstr( `var'," FOUNDATIONS "," FOUND ",1)
replace `var' = subinstr( `var'," FOUNDATION "," FOUND ",1)
replace `var' = subinstr( `var'," FRANCAISE "," FR ",1)
replace `var' = subinstr( `var'," FRANCAIS "," FR ",1)
replace `var' = subinstr( `var'," F LLI "," FRAT ",1)
replace `var' = subinstr( `var'," FLLI "," FRAT ",1)
replace `var' = subinstr( `var'," FRATELLI "," FRAT ",1)
replace `var' = subinstr( `var'," GEBRODERS "," GEBR ",1)
replace `var' = subinstr( `var'," GEBRODER "," GEBR ",1)
replace `var' = subinstr( `var'," GEBROEDERS "," GEBR ",1)
replace `var' = subinstr( `var'," GEBROEDER "," GEBR ",1)
replace `var' = subinstr( `var'," GEBRUDERS "," GEBR ",1)
replace `var' = subinstr( `var'," GEBRUDER "," GEBR ",1)
replace `var' = subinstr( `var'," GEBRUEDERS "," GEBR ",1)
replace `var' = subinstr( `var'," GEBRUEDER "," GEBR ",1)
replace `var' = subinstr( `var'," GEB "," GEBR ",1)
replace `var' = subinstr( `var'," GENERALA "," GEN ",1)
replace `var' = subinstr( `var'," GENERALES "," GEN ",1)
replace `var' = subinstr( `var'," GENERALE "," GEN ",1)
replace `var' = subinstr( `var'," GENERAL "," GEN ",1)
replace `var' = subinstr( `var'," GENERAUX "," GEN ",1)
replace `var' = subinstr( `var'," GESELLSCHAFT "," GES ",1)
replace `var' = subinstr( `var'," GEWERKSCHAFT "," GEW ",1)
replace `var' = subinstr( `var'," GAKKO HOJIN "," GH ",1)
replace `var' = subinstr( `var'," GAKKO HOUJIN "," GH ",1)
replace `var' = subinstr( `var'," GUTEHOFFNUNGSCHUETTE "," GHH ",1)
replace `var' = subinstr( `var'," GUTEHOFFNUNGSCHUTTE "," GHH ",1)
replace `var' = subinstr( `var'," GOMEI GAISHA "," GK ",1)
replace `var' = subinstr( `var'," GOMEI KAISHA "," GK ",1)
replace `var' = subinstr( `var'," GOSHI KAISHA "," GK ",1)
replace `var' = subinstr( `var'," GOUSHI GAISHA "," GK ",1)
replace `var' = subinstr( `var'," GESELLSCHAFT MBH "," GMBH ",1)
replace `var' = subinstr( `var'," GESELLSCHAFT MIT BESCHRANKTER HAFTUNG "," GMBH ",1)
replace `var' = subinstr( `var'," GROUPEMENT "," GRP ",1)
replace `var' = subinstr( `var'," GROUPMENT "," GRP ",1)
replace `var' = subinstr( `var'," HANDELSMAATSCHAPPIJ "," HANDL ",1)
replace `var' = subinstr( `var'," HANDELSMIJ "," HANDL ",1)
replace `var' = subinstr( `var'," HANDELS BOLAGET "," HB ",1)
replace `var' = subinstr( `var'," HANDELSBOLAGET "," HB ",1)
replace `var' = subinstr( `var'," HER MAJESTY THE QUEEN IN RIGHT OF CANADA AS REPRESENTED BY THE MINISTER OF "," CANADA MIN OF ",1)
replace `var' = subinstr( `var'," HER MAJESTY THE QUEEN "," UK ",1)
replace `var' = subinstr( `var'," INDUSTRIAS "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIALS "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIAL "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIALA "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIALE "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIALIZARE "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIALIZAREA "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIALI "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIEELE "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIEI "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIELS "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIELLES "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIELLE "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIELL "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIEL "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIER "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIES "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRII "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIJ "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIYAKH "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIYAM "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIYAMI "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIYA "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIYU "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIA "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRIE "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRI "," IND ",1)
replace `var' = subinstr( `var'," INDUSTRY "," IND ",1)
replace `var' = subinstr( `var'," INGENIERIA "," ING ",1)
replace `var' = subinstr( `var'," INGENIER "," ING ",1)
replace `var' = subinstr( `var'," INGENIEURS "," ING ",1)
replace `var' = subinstr( `var'," INGENIEURBUERO "," ING ",1)
replace `var' = subinstr( `var'," INGENIEURBUREAU "," ING ",1)
replace `var' = subinstr( `var'," INGENIEURBURO "," ING ",1)
replace `var' = subinstr( `var'," INGENIEURGESELLSCHAFT "," ING ",1)
replace `var' = subinstr( `var'," INGENIEURSBUREAU "," ING ",1)
replace `var' = subinstr( `var'," INGENIEURTECHNISCHES "," ING ",1)
replace `var' = subinstr( `var'," INGENIEURTECHNISCHE "," ING ",1)
replace `var' = subinstr( `var'," INGENIEUR "," ING ",1)
replace `var' = subinstr( `var'," INGENIOERFIRMAET "," ING ",1)
replace `var' = subinstr( `var'," INGENIORSFIRMAN "," ING ",1)
replace `var' = subinstr( `var'," INGENIORSFIRMA "," ING ",1)
replace `var' = subinstr( `var'," INGENJORSFIRMA "," ING ",1)
replace `var' = subinstr( `var'," INGINERIE "," ING ",1)
replace `var' = subinstr( `var'," INSTITUTE FRANCAISE "," INST FR ",1)
replace `var' = subinstr( `var'," INSTITUT FRANCAIS "," INST FR ",1)
replace `var' = subinstr( `var'," INSTITUTE NATIONALE "," INST NAT ",1)
replace `var' = subinstr( `var'," INSTITUT NATIONAL "," INST NAT ",1)
replace `var' = subinstr( `var'," INSTITUTAMI "," INST ",1)
replace `var' = subinstr( `var'," INSTITUTAMKH "," INST ",1)
replace `var' = subinstr( `var'," INSTITUTAM "," INST ",1)
replace `var' = subinstr( `var'," INSTITUTA "," INST ",1)
replace `var' = subinstr( `var'," INSTITUTES "," INST ",1)
replace `var' = subinstr( `var'," INSTITUTET "," INST ",1)
replace `var' = subinstr( `var'," INSTITUTE "," INST ",1)
replace `var' = subinstr( `var'," INSTITUTOM "," INST ",1)
replace `var' = subinstr( `var'," INSTITUTOV "," INST ",1)
replace `var' = subinstr( `var'," INSTITUTO "," INST ",1)
replace `var' = subinstr( `var'," INSTITUTT "," INST ",1)
replace `var' = subinstr( `var'," INSTITUTUL "," INST ",1)
replace `var' = subinstr( `var'," INSTITUTU "," INST ",1)
replace `var' = subinstr( `var'," INSTITUTY "," INST ",1)
replace `var' = subinstr( `var'," INSTITUT "," INST ",1)
replace `var' = subinstr( `var'," INSTITUUT "," INST ",1)
replace `var' = subinstr( `var'," INSTITZHT "," INST ",1)
replace `var' = subinstr( `var'," INSTYTUT "," INST ",1)
replace `var' = subinstr( `var'," INSINOORITOMISTO "," INSTMSTO ",1)
replace `var' = subinstr( `var'," INSTRUMENTS "," INSTR ",1)
replace `var' = subinstr( `var'," INSTRUMENTATION "," INSTR ",1)
replace `var' = subinstr( `var'," INSTRUMENTE "," INSTR ",1)
replace `var' = subinstr( `var'," INSTRUMENT "," INSTR ",1)
replace `var' = subinstr( `var'," INTERNATL "," INT ",1)
replace `var' = subinstr( `var'," INTERNACIONAL "," INT ",1)
replace `var' = subinstr( `var'," INTERNATIONAL "," INT ",1)
replace `var' = subinstr( `var'," INTERNATIONALEN "," INT ",1)
replace `var' = subinstr( `var'," INTERNATIONALE "," INT ",1)
replace `var' = subinstr( `var'," INTERNATIONAUX "," INT ",1)
replace `var' = subinstr( `var'," INTERNATIONELLA "," INT ",1)
replace `var' = subinstr( `var'," INTERNAZIONALE "," INT ",1)
replace `var' = subinstr( `var'," INTL "," INT ",1)
replace `var' = subinstr( `var'," INTREPRINDEREA "," INTR ",1)
replace `var' = subinstr( `var'," ISTITUTO "," IST ",1)
replace `var' = subinstr( `var'," ITALIANA "," ITAL ",1)
replace `var' = subinstr( `var'," ITALIANE "," ITAL ",1)
replace `var' = subinstr( `var'," ITALIANI "," ITAL ",1)
replace `var' = subinstr( `var'," ITALIANO "," ITAL ",1)
replace `var' = subinstr( `var'," ITALIENNE "," ITAL ",1)
replace `var' = subinstr( `var'," ITALIEN "," ITAL ",1)
replace `var' = subinstr( `var'," ITALIAN "," ITAL ",1)
replace `var' = subinstr( `var'," ITALIA "," ITAL ",1)
replace `var' = subinstr( `var'," ITALI "," ITAL ",1)
replace `var' = subinstr( `var'," ITALO "," ITAL ",1)
replace `var' = subinstr( `var'," ITALY "," ITAL ",1)
replace `var' = subinstr( `var'," JUNIOR "," JR ",1)
replace `var' = subinstr( `var'," KOMMANDIT BOLAG "," KB ",1)
replace `var' = subinstr( `var'," KOMMANDIT BOLAGET "," KB ",1)
replace `var' = subinstr( `var'," KOMMANDITBOLAGET "," KB ",1)
replace `var' = subinstr( `var'," KOMMANDITBOLAG "," KB ",1)
replace `var' = subinstr( `var'," KOMMANDIT GESELLSCHAFT "," KG ",1)
replace `var' = subinstr( `var'," KOMMANDITGESELLSCHAFT "," KG ",1)
replace `var' = subinstr( `var'," KOMMANDIT GESELLSCHAFT AUF AKTIEN "," KGAA ",1)
replace `var' = subinstr( `var'," KOMMANDITGESELLSCHAFT AUF AKTIEN "," KGAA ",1)
replace `var' = subinstr( `var'," KUTATO INTEZETE "," KI ",1)
replace `var' = subinstr( `var'," KUTATO INTEZET "," KI ",1)
replace `var' = subinstr( `var'," KUTATOINTEZETE "," KI ",1)
replace `var' = subinstr( `var'," KUTATOINTEZET "," KI ",1)
replace `var' = subinstr( `var'," KABUSHIKI GAISHA "," KK ",1)
replace `var' = subinstr( `var'," KABUSHIKI KAISHA "," KK ",1)
replace `var' = subinstr( `var'," KABUSHIKI GAISYA "," KK ",1)
replace `var' = subinstr( `var'," KABUSHIKI KAISYA "," KK ",1)
replace `var' = subinstr( `var'," KABUSHIKIGAISHA "," KK ",1)
replace `var' = subinstr( `var'," KABUSHIKIKAISHA "," KK ",1)
replace `var' = subinstr( `var'," KABUSHIKIGAISYA "," KK ",1)
replace `var' = subinstr( `var'," KABUSHIKIKAISYA "," KK ",1)
replace `var' = subinstr( `var'," KOMBINATU "," KOMB ",1)
replace `var' = subinstr( `var'," KOMBINATY "," KOMB ",1)
replace `var' = subinstr( `var'," KOMBINAT "," KOMB ",1)
replace `var' = subinstr( `var'," KONINKLIJKE "," KONINK ",1)
replace `var' = subinstr( `var'," KONCERNOVY PODNIK "," KP ",1)
replace `var' = subinstr( `var'," KUNSTSTOFFTECHNIK "," KUNST ",1)
replace `var' = subinstr( `var'," KUNSTSTOFF "," KUNST ",1)
replace `var' = subinstr( `var'," LABORATOIRES "," LAB ",1)
replace `var' = subinstr( `var'," LABORATOIRE "," LAB ",1)
replace `var' = subinstr( `var'," LABORATOIR "," LAB ",1)
replace `var' = subinstr( `var'," LABORATORIEI "," LAB ",1)
replace `var' = subinstr( `var'," LABORATORIES "," LAB ",1)
replace `var' = subinstr( `var'," LABORATORII "," LAB ",1)
replace `var' = subinstr( `var'," LABORATORIJ "," LAB ",1)
replace `var' = subinstr( `var'," LABORATORIOS "," LAB ",1)
replace `var' = subinstr( `var'," LABORATORIO "," LAB ",1)
replace `var' = subinstr( `var'," LABORATORIUM "," LAB ",1)
replace `var' = subinstr( `var'," LABORATORI "," LAB ",1)
replace `var' = subinstr( `var'," LABORATORY "," LAB ",1)
replace `var' = subinstr( `var'," LABORTORI "," LAB ",1)
replace `var' = subinstr( `var'," LAVORAZA "," LAVORAZ ",1)
replace `var' = subinstr( `var'," LAVORAZIONE "," LAVORAZ ",1)
replace `var' = subinstr( `var'," LAVORAZIONI "," LAVORAZ ",1)
replace `var' = subinstr( `var'," LAVORAZIO "," LAVORAZ ",1)
replace `var' = subinstr( `var'," LAVORAZI "," LAVORAZ ",1)
replace `var' = subinstr( `var'," LIMITED PARTNERSHIP "," LP ",1)
replace `var' = subinstr( `var'," LIMITED "," LTD ",1)
replace `var' = subinstr( `var'," LTD LTEE "," LTD ",1)
replace `var' = subinstr( `var'," MASCHINENVERTRIEB "," MASCH ",1)
replace `var' = subinstr( `var'," MASCHINENBAUANSTALT "," MASCHBAU ",1)
replace `var' = subinstr( `var'," MASCHINENBAU "," MASCHBAU ",1)
replace `var' = subinstr( `var'," MASCHINENFABRIEK "," MASCHFAB ",1)
replace `var' = subinstr( `var'," MASCHINENFABRIKEN "," MASCHFAB ",1)
replace `var' = subinstr( `var'," MASCHINENFABRIK "," MASCHFAB ",1)
replace `var' = subinstr( `var'," MASCHINENFAB "," MASCHFAB ",1)
replace `var' = subinstr( `var'," MASCHINEN "," MASCH ",1)
replace `var' = subinstr( `var'," MASCHIN "," MASCH ",1)
replace `var' = subinstr( `var'," MIT BESCHRANKTER HAFTUNG "," MBH ",1)
replace `var' = subinstr( `var'," MANUFACTURINGS "," MFG ",1)
replace `var' = subinstr( `var'," MANUFACTURING "," MFG ",1)
replace `var' = subinstr( `var'," MANIFATTURAS "," MFR ",1)
replace `var' = subinstr( `var'," MANIFATTURA "," MFR ",1)
replace `var' = subinstr( `var'," MANIFATTURE "," MFR ",1)
replace `var' = subinstr( `var'," MANUFACTURAS "," MFR ",1)
replace `var' = subinstr( `var'," MANUFACTURERS "," MFR ",1)
replace `var' = subinstr( `var'," MANUFACTURER "," MFR ",1)
replace `var' = subinstr( `var'," MANUFACTURES "," MFR ",1)
replace `var' = subinstr( `var'," MANUFACTURE "," MFR ",1)
replace `var' = subinstr( `var'," MANUFATURA "," MFR ",1)
replace `var' = subinstr( `var'," MAATSCHAPPIJ "," MIJ ",1)
replace `var' = subinstr( `var'," MEDICAL "," MED ",1)
replace `var' = subinstr( `var'," MINISTERE "," MIN ",1)
replace `var' = subinstr( `var'," MINISTERIUM "," MIN ",1)
replace `var' = subinstr( `var'," MINISTERO "," MIN ",1)
replace `var' = subinstr( `var'," MINISTERSTVAKH "," MIN ",1)
replace `var' = subinstr( `var'," MINISTERSTVAM "," MIN ",1)
replace `var' = subinstr( `var'," MINISTERSTVAMI "," MIN ",1)
replace `var' = subinstr( `var'," MINISTERSTVA "," MIN ",1)
replace `var' = subinstr( `var'," MINISTERSTVE "," MIN ",1)
replace `var' = subinstr( `var'," MINISTERSTVO "," MIN ",1)
replace `var' = subinstr( `var'," MINISTERSTVOM "," MIN ",1)
replace `var' = subinstr( `var'," MINISTERSTVU "," MIN ",1)
replace `var' = subinstr( `var'," MINISTERSTV "," MIN ",1)
replace `var' = subinstr( `var'," MINISTERSTWO "," MIN ",1)
replace `var' = subinstr( `var'," MINISTERUL "," MIN ",1)
replace `var' = subinstr( `var'," MINISTRE "," MIN ",1)
replace `var' = subinstr( `var'," MINISTRY "," MIN ",1)
replace `var' = subinstr( `var'," MINISTER "," MIN ",1)
replace `var' = subinstr( `var'," MAGYAR TUDOMANYOS AKADEMIA "," MTA ",1)
replace `var' = subinstr( `var'," NATIONAAL "," NAT ",1)
replace `var' = subinstr( `var'," NATIONAL "," NAT ",1)
replace `var' = subinstr( `var'," NATIONALE "," NAT ",1)
replace `var' = subinstr( `var'," NATIONAUX "," NAT ",1)
replace `var' = subinstr( `var'," NATL "," NAT ",1)
replace `var' = subinstr( `var'," NAZIONALE "," NAZ ",1)
replace `var' = subinstr( `var'," NAZIONALI "," NAZ ",1)
replace `var' = subinstr( `var'," NORDDEUTSCH "," NORDDEUT ",1)
replace `var' = subinstr( `var'," NORDDEUTSCHE "," NORDDEUT ",1)
replace `var' = subinstr( `var'," NORDDEUTSCHER "," NORDDEUT ",1)
replace `var' = subinstr( `var'," NORDDEUTSCHES "," NORDDEUT ",1)
replace `var' = subinstr( `var'," NARODNI PODNIK "," NP ",1)
replace `var' = subinstr( `var'," NARODNIJ PODNIK "," NP ",1)
replace `var' = subinstr( `var'," NARODNY PODNIK "," NP ",1)
replace `var' = subinstr( `var'," NAAMLOOSE VENOOTSCHAP "," NV ",1)
replace `var' = subinstr( `var'," NAAMLOZE VENNOOTSCHAP "," NV ",1)
replace `var' = subinstr( `var'," N V "," NV ",1)
replace `var' = subinstr( `var'," OESTERREICHISCHES "," OESTERR ",1)
replace `var' = subinstr( `var'," OESTERREICHISCHE "," OESTERR ",1)
replace `var' = subinstr( `var'," OESTERREICHISCH "," OESTERR ",1)
replace `var' = subinstr( `var'," OESTERREICH "," OESTERR ",1)
replace `var' = subinstr( `var'," OSTERREICHISCHES "," OESTERR ",1)
replace `var' = subinstr( `var'," OSTERREICHISCHE "," OESTERR ",1)
replace `var' = subinstr( `var'," OSTERREICHISCH "," OESTERR ",1)
replace `var' = subinstr( `var'," OSTERREICH "," OESTERR ",1)
replace `var' = subinstr( `var'," OFFICINE MECCANICA "," OFF MEC ",1)
replace `var' = subinstr( `var'," OFFICINE MECCANICHE "," OFF MEC ",1)
replace `var' = subinstr( `var'," OFFICINE NATIONALE "," OFF NAT ",1)
replace `var' = subinstr( `var'," OFFENE HANDELSGESELLSCHAFT "," OHG ",1)
replace `var' = subinstr( `var'," ONTWIKKELINGSBUREAU "," ONTWIK ",1)
replace `var' = subinstr( `var'," ONTWIKKELINGS "," ONTWIK ",1)
replace `var' = subinstr( `var'," OBOROVY PODNIK "," OP ",1)
replace `var' = subinstr( `var'," ORGANISATIE "," ORG ",1)
replace `var' = subinstr( `var'," ORGANISATIONS "," ORG ",1)
replace `var' = subinstr( `var'," ORGANISATION "," ORG ",1)
replace `var' = subinstr( `var'," ORGANIZATIONS "," ORG ",1)
replace `var' = subinstr( `var'," ORGANIZATION "," ORG ",1)
replace `var' = subinstr( `var'," ORGANIZZAZIONE "," ORG ",1)
replace `var' = subinstr( `var'," OSAKEYHTIO "," OY ",1)
replace `var' = subinstr( `var'," PHARMACEUTICALS "," PHARM ",1)
replace `var' = subinstr( `var'," PHARMACEUTICAL "," PHARM ",1)
replace `var' = subinstr( `var'," PHARMACEUTICA "," PHARM ",1)
replace `var' = subinstr( `var'," PHARMACEUTIQUES "," PHARM ",1)
replace `var' = subinstr( `var'," PHARMACEUTIQUE "," PHARM ",1)
replace `var' = subinstr( `var'," PHARMAZEUTIKA "," PHARM ",1)
replace `var' = subinstr( `var'," PHARMAZEUTISCHEN "," PHARM ",1)
replace `var' = subinstr( `var'," PHARMAZEUTISCHE "," PHARM ",1)
replace `var' = subinstr( `var'," PHARMAZEUTISCH "," PHARM ",1)
replace `var' = subinstr( `var'," PHARMAZIE "," PHARM ",1)
replace `var' = subinstr( `var'," PUBLIC LIMITED COMPANY "," PLC ",1)
replace `var' = subinstr( `var'," PRELUCRAREA "," PRELUC ",1)
replace `var' = subinstr( `var'," PRELUCRARE "," PRELUC ",1)
replace `var' = subinstr( `var'," PRODOTTI "," PROD ",1)
replace `var' = subinstr( `var'," PRODUCE "," PROD ",1)
replace `var' = subinstr( `var'," PRODUCTS "," PROD ",1)
replace `var' = subinstr( `var'," PRODUCT "," PROD ",1)
replace `var' = subinstr( `var'," PRODUCTAS "," PROD ",1)
replace `var' = subinstr( `var'," PRODUCTA "," PROD ",1)
replace `var' = subinstr( `var'," PRODUCTIE "," PROD ",1)
replace `var' = subinstr( `var'," PRODUCTOS "," PROD ",1)
replace `var' = subinstr( `var'," PRODUCTO "," PROD ",1)
replace `var' = subinstr( `var'," PRODUCTORES "," PROD ",1)
replace `var' = subinstr( `var'," PRODUIT CHIMIQUES "," PROD CHIM ",1)
replace `var' = subinstr( `var'," PRODUIT CHIMIQUE "," PROD CHIM ",1)
replace `var' = subinstr( `var'," PRODUITS "," PROD ",1)
replace `var' = subinstr( `var'," PRODUIT "," PROD ",1)
replace `var' = subinstr( `var'," PRODUKCJI "," PROD ",1)
replace `var' = subinstr( `var'," PRODUKTER "," PROD ",1)
replace `var' = subinstr( `var'," PRODUKTE "," PROD ",1)
replace `var' = subinstr( `var'," PRODUKT "," PROD ",1)
replace `var' = subinstr( `var'," PRODUSE "," PROD ",1)
replace `var' = subinstr( `var'," PRODUTOS "," PROD ",1)
replace `var' = subinstr( `var'," PRODUCTIONS "," PRODN ",1)
replace `var' = subinstr( `var'," PRODUCTION "," PRODN ",1)
replace `var' = subinstr( `var'," PRODUKTIONS "," PRODN ",1)
replace `var' = subinstr( `var'," PRODUKTION "," PRODN ",1)
replace `var' = subinstr( `var'," PRODUZIONI "," PRODN ",1)
replace `var' = subinstr( `var'," PROIECTARE "," PROI ",1)
replace `var' = subinstr( `var'," PROIECTARI "," PROI ",1)
replace `var' = subinstr( `var'," PRZEDSIEBIOSTWO "," PRZEDSIEB ",1)
replace `var' = subinstr( `var'," PRZEMYSLU "," PRZEYM ",1)
replace `var' = subinstr( `var'," PROPRIETARY "," PTY ",1)
replace `var' = subinstr( `var'," PERSONENVENNOOTSCHAP MET "," PVBA ",1)
replace `var' = subinstr( `var'," BEPERKTE AANSPRAKELIJKHEID "," PVBA ",1)
replace `var' = subinstr( `var'," REALISATIONS "," REAL ",1)
replace `var' = subinstr( `var'," REALISATION "," REAL ",1)
replace `var' = subinstr( `var'," RECHERCHES ET DEVELOPMENTS "," R&D ",1)
replace `var' = subinstr( `var'," RECHERCHE ET DEVELOPMENT "," R&D ",1)
replace `var' = subinstr( `var'," RECHERCHES ET DEVELOPPEMENTS "," R&D ",1)
replace `var' = subinstr( `var'," RECHERCHE ET DEVELOPPEMENT "," R&D ",1)
replace `var' = subinstr( `var'," RESEARCH & DEVELOPMENT "," R&D ",1)
replace `var' = subinstr( `var'," RESEARCH AND DEVELOPMENT "," R&D ",1)
replace `var' = subinstr( `var'," RESEARCH "," RES ",1)
replace `var' = subinstr( `var'," RECHERCHES "," RECH ",1)
replace `var' = subinstr( `var'," RECHERCHE "," RECH ",1)
replace `var' = subinstr( `var'," RIJKSUNIVERSITEIT "," RIJKSUNIV ",1)
replace `var' = subinstr( `var'," SECRETATY "," SECRETARY ",1)
replace `var' = subinstr( `var'," SECRETRY "," SECRETARY ",1)
replace `var' = subinstr( `var'," SECREATRY "," SECRETARY ",1)
replace `var' = subinstr( `var'," SOCIETE ANONYME DITE "," SA ",1)
replace `var' = subinstr( `var'," SOCIEDAD ANONIMA "," SA ",1)
replace `var' = subinstr( `var'," SOCIETE ANONYME "," SA ",1)
replace `var' = subinstr( `var'," SOCIETE A RESPONSABILITE LIMITEE "," SARL ",1)
replace `var' = subinstr( `var'," SOCIETE A RESPONSIBILITE LIMITEE "," SARL ",1)
replace `var' = subinstr( `var'," SOCIETA IN ACCOMANDITA SEMPLICE "," SAS ",1)
replace `var' = subinstr( `var'," SCHWEIZERISCHES "," SCHWEIZ ",1)
replace `var' = subinstr( `var'," SCHWEIZERISCHER "," SCHWEIZ ",1)
replace `var' = subinstr( `var'," SCHWEIZERISCHE "," SCHWEIZ ",1)
replace `var' = subinstr( `var'," SCHWEIZERISCH "," SCHWEIZ ",1)
replace `var' = subinstr( `var'," SCHWEIZER "," SCHWEIZ ",1)
replace `var' = subinstr( `var'," SCIENCES "," SCI ",1)
replace `var' = subinstr( `var'," SCIENCE "," SCI ",1)
replace `var' = subinstr( `var'," SCIENTIFICA "," SCI ",1)
replace `var' = subinstr( `var'," SCIENTIFIC "," SCI ",1)
replace `var' = subinstr( `var'," SCIENTIFIQUES "," SCI ",1)
replace `var' = subinstr( `var'," SCIENTIFIQUE "," SCI ",1)
replace `var' = subinstr( `var'," SHADAN HOJIN "," SH ",1)
replace `var' = subinstr( `var'," SIDERURGICAS "," SIDER ",1)
replace `var' = subinstr( `var'," SIDERURGICA "," SIDER ",1)
replace `var' = subinstr( `var'," SIDERURGIC "," SIDER ",1)
replace `var' = subinstr( `var'," SIDERURGIE "," SIDER ",1)
replace `var' = subinstr( `var'," SIDERURGIQUE "," SIDER ",1)
replace `var' = subinstr( `var'," SOCIETA IN NOME COLLECTIVO "," SNC ",1)
replace `var' = subinstr( `var'," SOCIETE EN NOM COLLECTIF "," SNC ",1)
replace `var' = subinstr( `var'," SOCIETE ALSACIENNE "," SOC ALSAC ",1)
replace `var' = subinstr( `var'," SOCIETE APPLICATION "," SOC APPL ",1)
replace `var' = subinstr( `var'," SOCIETA APPLICAZIONE "," SOC APPL ",1)
replace `var' = subinstr( `var'," SOCIETE AUXILIAIRE "," SOC AUX ",1)
replace `var' = subinstr( `var'," SOCIETE CHIMIQUE "," SOC CHIM ",1)
replace `var' = subinstr( `var'," SOCIEDAD CIVIL "," SOC CIV ",1)
replace `var' = subinstr( `var'," SOCIETE CIVILE "," SOC CIV ",1)
replace `var' = subinstr( `var'," SOCIETE COMMERCIALES "," SOC COMML ",1)
replace `var' = subinstr( `var'," SOCIETE COMMERCIALE "," SOC COMML ",1)
replace `var' = subinstr( `var'," SOCIEDAD ESPANOLA "," SOC ESPAN ",1)
replace `var' = subinstr( `var'," SOCIETE ETUDES "," SOC ETUD ",1)
replace `var' = subinstr( `var'," SOCIETE ETUDE "," SOC ETUD ",1)
replace `var' = subinstr( `var'," SOCIETE EXPLOITATION "," SOC EXPL ",1)
replace `var' = subinstr( `var'," SOCIETE GENERALE "," SOC GEN ",1)
replace `var' = subinstr( `var'," SOCIETE INDUSTRIELLES "," SOC IND ",1)
replace `var' = subinstr( `var'," SOCIETE INDUSTRIELLE "," SOC IND ",1)
replace `var' = subinstr( `var'," SOCIETE MECANIQUES "," SOC MEC ",1)
replace `var' = subinstr( `var'," SOCIETE MECANIQUE "," SOC MEC ",1)
replace `var' = subinstr( `var'," SOCIETE NATIONALE "," SOC NAT ",1)
replace `var' = subinstr( `var'," SOCIETE NOUVELLE "," SOC NOUV ",1)
replace `var' = subinstr( `var'," SOCIETE PARISIENNE "," SOC PARIS ",1)
replace `var' = subinstr( `var'," SOCIETE PARISIENN "," SOC PARIS ",1)
replace `var' = subinstr( `var'," SOCIETE PARISIEN "," SOC PARIS ",1)
replace `var' = subinstr( `var'," SOCIETE TECHNIQUES "," SOC TECH ",1)
replace `var' = subinstr( `var'," SOCIETE TECHNIQUE "," SOC TECH ",1)
replace `var' = subinstr( `var'," SDRUZENI PODNIKU "," SP ",1)
replace `var' = subinstr( `var'," SDRUZENI PODNIK "," SP ",1)
replace `var' = subinstr( `var'," SOCIETA PER AZIONI "," SPA ",1)
replace `var' = subinstr( `var'," SPITALUL "," SPITAL ",1)
replace `var' = subinstr( `var'," SOCIETE PRIVEE A RESPONSABILITE LIMITEE "," SPRL ",1)
replace `var' = subinstr( `var'," SOCIEDAD DE RESPONSABILIDAD LIMITADA "," SRL ",1)
replace `var' = subinstr( `var'," STIINTIFICA "," STIINT ",1)
replace `var' = subinstr( `var'," SUDDEUTSCHES "," SUDDEUT ",1)
replace `var' = subinstr( `var'," SUDDEUTSCHER "," SUDDEUT ",1)
replace `var' = subinstr( `var'," SUDDEUTSCHE "," SUDDEUT ",1)
replace `var' = subinstr( `var'," SUDDEUTSCH "," SUDDEUT ",1)
replace `var' = subinstr( `var'," SOCIEDADE "," SOC ",1)
replace `var' = subinstr( `var'," SOCIEDAD "," SOC ",1)
replace `var' = subinstr( `var'," SOCIETA "," SOC ",1)
replace `var' = subinstr( `var'," SOCIETE "," SOC ",1)
replace `var' = subinstr( `var'," SOCIETY "," SOC ",1)
replace `var' = subinstr( `var'," SA DITE "," SA ",1)
replace `var' = subinstr( `var'," TECHNICAL "," TECH ",1)
replace `var' = subinstr( `var'," TECHNICO "," TECH ",1)
replace `var' = subinstr( `var'," TECHNICZNY "," TECH ",1)
replace `var' = subinstr( `var'," TECHNIKAI "," TECH ",1)
replace `var' = subinstr( `var'," TECHNIKI "," TECH ",1)
replace `var' = subinstr( `var'," TECHNIK "," TECH ",1)
replace `var' = subinstr( `var'," TECHNIQUES "," TECH ",1)
replace `var' = subinstr( `var'," TECHNIQUE "," TECH ",1)
replace `var' = subinstr( `var'," TECHNISCHES "," TECH ",1)
replace `var' = subinstr( `var'," TECHNISCHE "," TECH ",1)
replace `var' = subinstr( `var'," TECHNISCH "," TECH ",1)
replace `var' = subinstr( `var'," TECHNOLOGY "," TECH ",1)
replace `var' = subinstr( `var'," TECHNOLOGIES "," TECH ",1)
replace `var' = subinstr( `var'," TELECOMMUNICATIONS "," TELECOM ",1)
replace `var' = subinstr( `var'," TELECOMMUNICACION "," TELECOM ",1)
replace `var' = subinstr( `var'," TELECOMMUNICATION "," TELECOM ",1)
replace `var' = subinstr( `var'," TELECOMMUNICAZIONI "," TELECOM ",1)
replace `var' = subinstr( `var'," TELECOMUNICAZIONI "," TELECOM ",1)
replace `var' = subinstr( `var'," TRUSTUL "," TRUST ",1)
replace `var' = subinstr( `var'," UNITED KINGDOM "," UK ",1)
replace `var' = subinstr( `var'," SECRETARY OF STATE FOR "," UK SEC FOR ",1)
replace `var' = subinstr( `var'," UNIVERSIDADE "," UNIV ",1)
replace `var' = subinstr( `var'," UNIVERSIDAD "," UNIV ",1)
replace `var' = subinstr( `var'," UNIVERSITA DEGLI STUDI "," UNIV ",1)
replace `var' = subinstr( `var'," UNIVERSITAET "," UNIV ",1)
replace `var' = subinstr( `var'," UNIVERSITAIRE "," UNIV ",1)
replace `var' = subinstr( `var'," UNIVERSITAIR "," UNIV ",1)
replace `var' = subinstr( `var'," UNIVERSITATEA "," UNIV ",1)
replace `var' = subinstr( `var'," UNIVERSITEIT "," UNIV ",1)
replace `var' = subinstr( `var'," UNIVERSITETAMI "," UNIV ",1)
replace `var' = subinstr( `var'," UNIVERSITETAM "," UNIV ",1)
replace `var' = subinstr( `var'," UNIVERSITETE "," UNIV ",1)
replace `var' = subinstr( `var'," UNIVERSITETOM "," UNIV ",1)
replace `var' = subinstr( `var'," UNIVERSITETOV "," UNIV ",1)
replace `var' = subinstr( `var'," UNIVERSITETU "," UNIV ",1)
replace `var' = subinstr( `var'," UNIVERSITETY "," UNIV ",1)
replace `var' = subinstr( `var'," UNIVERSITETA "," UNIV ",1)
replace `var' = subinstr( `var'," UNIVERSITAT "," UNIV ",1)
replace `var' = subinstr( `var'," UNIVERSITET "," UNIV ",1)
replace `var' = subinstr( `var'," UNIVERSITE "," UNIV ",1)
replace `var' = subinstr( `var'," UNIVERSITY "," UNIV ",1)
replace `var' = subinstr( `var'," UNIVERSITA "," UNIV ",1)
replace `var' = subinstr( `var'," UNIWERSYTET "," UNIV ",1)
replace `var' = subinstr( `var'," UNITED STATES OF AMERICA ADMINISTRATOR "," US ADMIN ",1)
replace `var' = subinstr( `var'," UNITED STATES OF AMERICA AS REPRESENTED BY THE ADMINISTRATOR "," US ADMIN ",1)
replace `var' = subinstr( `var'," UNITED STATES OF AMERICA AS REPRESENTED BY THE DEPT "," US DEPT ",1)
replace `var' = subinstr( `var'," UNITED STATES OF AMERICA AS REPRESENTED BY THE UNITED STATES DEPT "," US DEPT ",1)
replace `var' = subinstr( `var'," UNITED STATES OF AMERICAN AS REPRESENTED BY THE UNITED STATES DEPT "," US DEPT ",1)
replace `var' = subinstr( `var'," UNITED STATES GOVERNMENT AS REPRESENTED BY THE SECRETARY OF "," US SEC ",1)
replace `var' = subinstr( `var'," UNITED STATES OF AMERICA REPRESENTED BY THE SECRETARY "," US SEC ",1)
replace `var' = subinstr( `var'," UNITED STATES OF AMERICA AS REPRESENTED BY THE SECRETARY "," US SEC ",1)
replace `var' = subinstr( `var'," UNITED STATES OF AMERICAS AS REPRESENTED BY THE SECRETARY "," US SEC ",1)
replace `var' = subinstr( `var'," UNITES STATES OF AMERICA AS REPRESENTED BY THE SECRETARY "," US SEC ",1)
replace `var' = subinstr( `var'," UNITED STATES OF AMERICA SECRETARY OF "," US SEC ",1)
replace `var' = subinstr( `var'," UNITED STATES OF AMERICA "," USA ",1)
replace `var' = subinstr( `var'," UNITED STATES "," USA ",1)
replace `var' = subinstr( `var'," UTILAJE "," UTIL ",1)
replace `var' = subinstr( `var'," UTILAJ "," UTIL ",1)
replace `var' = subinstr( `var'," UTILISATIONS VOLKSEIGENER BETRIEBE "," VEB ",1)
replace `var' = subinstr( `var'," UTILISATION VOLKSEIGENER BETRIEBE "," VEB ",1)
replace `var' = subinstr( `var'," VEB KOMBINAT "," VEB KOMB ",1)
replace `var' = subinstr( `var'," VEREENIGDE "," VER ",1)
replace `var' = subinstr( `var'," VEREINIGTES VEREINIGUNG "," VER ",1)
replace `var' = subinstr( `var'," VEREINIGTE VEREINIGUNG "," VER ",1)
replace `var' = subinstr( `var'," VEREIN "," VER ",1)
replace `var' = subinstr( `var'," VERENIGING "," VER ",1)
replace `var' = subinstr( `var'," VERWALTUNGEN "," VERW ",1)
replace `var' = subinstr( `var'," VERWALTUNGS "," VERW ",1)
replace `var' = subinstr( `var'," VERWERTUNGS "," VERW ",1)
replace `var' = subinstr( `var'," VERWALTUNGSGESELLSCHAFT "," VERW GES ",1)
replace `var' = subinstr( `var'," VYZK USTAV "," VU ",1)
replace `var' = subinstr( `var'," VYZKUMNY USTAV "," VU ",1)
replace `var' = subinstr( `var'," VYZKUMNYUSTAV "," VU ",1)
replace `var' = subinstr( `var'," VEREINIGUNG VOLKSEIGENER BETRIEBUNG "," VVB ",1)
replace `var' = subinstr( `var'," VYZK VYVOJOVY USTAV "," VVU ",1)
replace `var' = subinstr( `var'," VYZKUMNY VYVOJOVY USTAV "," VVU ",1)
replace `var' = subinstr( `var'," WERKZEUGMASCHINENKOMBINAT "," WERKZ MASCH KOMB ",1)
replace `var' = subinstr( `var'," WERKZEUGMASCHINENFABRIK "," WERKZ MASCHFAB ",1)
replace `var' = subinstr( `var'," WESTDEUTSCHES "," WESTDEUT ",1)
replace `var' = subinstr( `var'," WESTDEUTSCHER "," WESTDEUT ",1)
replace `var' = subinstr( `var'," WESTDEUTSCHE "," WESTDEUT ",1)
replace `var' = subinstr( `var'," WESTDEUTSCH "," WESTDEUT ",1)
replace `var' = subinstr( `var'," WISSENSCHAFTLICHE "," WISS ",1)
replace `var' = subinstr( `var'," WISSENSCHAFTLICHES TECHNISCHES ZENTRUM "," WTZ ",1)
replace `var' = subinstr( `var'," YUGEN KAISHA "," YG YUGEN GAISHA ",1)
replace `var' = subinstr( `var'," YUUGEN GAISHA "," YG YUGEN GAISHA ",1)
replace `var' = subinstr( `var'," YUUGEN KAISHA "," YG YUGEN GAISHA ",1)
replace `var' = subinstr( `var'," YUUGEN KAISYA "," YG YUGEN GAISHA ",1)
replace `var' = subinstr( `var'," ZAVODU "," ZAVOD ",1)
replace `var' = subinstr( `var'," ZAVODY "," ZAVOD ",1)
replace `var' = subinstr( `var'," ZENTRALES "," ZENT ",1)
replace `var' = subinstr( `var'," ZENTRALE "," ZENT ",1)
replace `var' = subinstr( `var'," ZENTRALEN "," ZENT ",1)
replace `var' = subinstr( `var'," ZENTRALNA "," ZENT ",1)
replace `var' = subinstr( `var'," ZENTRUM "," ZENT ",1)
replace `var' = subinstr( `var'," ZENTRALINSTITUT "," ZENT INST ",1)
replace `var' = subinstr( `var'," ZENTRALLABORATORIUM "," ZENT LAB ",1)
replace `var' = subinstr( `var'," ZAIDAN HOJIN "," ZH ",1)
replace `var' = subinstr( `var'," ZAIDAN HOUJIN "," ZH ",1)
replace `var' = subinstr( `var'," LIMITED "," LTD ",1)
replace `var' = subinstr( `var'," LIMITADA "," LTDA ",1)
replace `var' = subinstr( `var'," SECRETARY "," SEC ",1)


********************************
****** STANDARDIZE ENTITY ******
********************************

** UNITED KINGDOM
replace `var' = subinstr( `var', " PUBLIC LIMITED ", " PLC ", 1)
replace `var' = subinstr( `var', " PUBLIC LIABILITY COMPANY ", " PLC ", 1)
replace `var' = subinstr( `var', " HOLDINGS ", " HLDGS ", 1)
replace `var' = subinstr( `var', " HOLDING ", " HLDGS ", 1)
replace `var' = subinstr( `var', " GREAT BRITAIN ", " GB ", 1)
replace `var' = subinstr( `var', " LTD CO ", " CO LTD ", 1)

** SPANISH
replace `var' = subinstr( `var', " SOC LIMITADA ", " SL ", 1)
replace `var' = subinstr( `var', " SOC EN COMMANDITA ", " SC ", 1)
replace `var' = subinstr( `var', " & CIA ", " CO ", 1)

** ITALIAN
replace `var' = subinstr( `var', " SOC IN ACCOMANDITA PER AZIONI ", " SA ", 1)
replace `var' = subinstr( `var', " SAPA ", " SA ", 1)
replace `var' = subinstr( `var', " SOC A RESPONSABILIT¿ LIMITATA ", " SRL ", 1)

** SWEDISH
replace `var' = subinstr( `var', " HANDELSBOLAG ", " HB  ", 1)

** GERMAN
replace `var' = subinstr( `var', " KOMANDIT GESELLSCHAFT ", " KG ", 1)
replace `var' = subinstr( `var', " KOMANDITGESELLSCHAFT ", " KG ", 1)
replace `var' = subinstr( `var', " EINGETRAGENE GENOSSENSCHAFT ", " EG ", 1)
replace `var' = subinstr( `var', " GENOSSENSCHAFT ", " EG ", 1)
replace `var' = subinstr( `var', " GESELLSCHAFT M B H ", " GMBH ", 1)
replace `var' = subinstr( `var', " OFFENE HANDELS GESELLSCHAFT ", " OHG ", 1)
replace `var' = subinstr( `var', " GESMBH ", " GMBH ", 1)
replace `var' = subinstr( `var', " GESELLSCHAFT BURGERLICHEN RECHTS ", " GBR ", 1)
replace `var' = subinstr( `var', " GESELLSCHAFT ", " GMBH ", 1)
* The following is common format. If conflict assume GMBH & CO KG over GMBH & CO OHG as more common.
replace `var' = subinstr( `var', " GMBH CO KG ", " GMBH & CO KG ", 1)
replace `var' = subinstr( `var', " GMBH COKG ", " GMBH & CO KG ", 1)
replace `var' = subinstr( `var', " GMBH U CO KG ", " GMBH & CO KG ", 1)
replace `var' = subinstr( `var', " GMBH U COKG ", " GMBH & CO KG ", 1)
replace `var' = subinstr( `var', " GMBH U CO ", " GMBH & CO KG ", 1)
replace `var' = subinstr( `var', " GMBH CO ", " GMBH & CO KG ", 1)
replace `var' = subinstr( `var', " AG CO KG ", " AG & CO KG ", 1)
replace `var' = subinstr( `var', " AG COKG ", " AG & CO KG ", 1)
replace `var' = subinstr( `var', " AG U CO KG ", " AG & CO KG ", 1)
replace `var' = subinstr( `var', " AG U COKG ", " AG & CO KG ", 1)
replace `var' = subinstr( `var', " AG U CO ", " AG & CO KG ", 1)
replace `var' = subinstr( `var', " AG CO ", " AG & CO KG ", 1)
replace `var' = subinstr( `var', " GMBH CO OHG ", " GMBH &CO OHG ", 1)
replace `var' = subinstr( `var', " GMBH COOHG ", " GMBH & CO OHG ", 1)
replace `var' = subinstr( `var', " GMBH U CO OHG ", " GMBH & CO OHG ", 1)
replace `var' = subinstr( `var', " GMBH U COOHG ", " GMBH & CO OHG ", 1)
replace `var' = subinstr( `var', " AG CO OHG ", " AG & CO OHG ", 1)
replace `var' = subinstr( `var', " AG COOHG ", " AG & CO OHG ", 1)
replace `var' = subinstr( `var', " AG U CO OHG ", " AG & CO OHG ", 1)
replace `var' = subinstr( `var', " AG U COOHG ", " AG & CO OHG ", 1)

** FRENCH and BELGIAN
replace `var' = subinstr( `var', " SOCIETE ANONYME SIMPLIFIEE ", " SAS ", 1)
replace `var' = subinstr( `var', " SOC ANONYME ", " SA ", 1)
replace `var' = subinstr( `var', " STE ANONYME ", " SA ", 1)
replace `var' = subinstr( `var', " SARL UNIPERSONNELLE ", " SARLU ", 1)
replace `var' = subinstr( `var', " SOC PAR ACTIONS SIMPLIFIEES ", " SAS ", 1)
replace `var' = subinstr( `var', " SAS UNIPERSONNELLE ", " SASU ", 1)
replace `var' = subinstr( `var', " ENTREPRISE UNIPERSONNELLE A RESPONSABILITE LIMITEE ", " EURL ", 1)
replace `var' = subinstr( `var', " SOCIETE CIVILE IMMOBILIERE ", " SCI ", 1)
replace `var' = subinstr( `var', " GROUPEMENT D INTERET ECONOMIQUE ", " GIE ", 1)
replace `var' = subinstr( `var', " SOCIETE EN PARTICIPATION ", " SP ", 1)
replace `var' = subinstr( `var', " SOCIETE EN COMMANDITE SIMPLE ", " SCS ", 1)
replace `var' = subinstr( `var', " ANONYME DITE ", " SA ", 1)
replace `var' = subinstr( `var', " SOC DITE ", " SA ", 1)
replace `var' = subinstr( `var', " & CIE ", " CO ", 1)

** BELGIAN
** Note: the Belgians use a lot of French endings, so handle as above.
** Also, they use NV (belgian) and SA (french) interchangably, so standardise to SA

replace `var' = subinstr( `var', " BV BEPERKTE AANSPRAKELIJKHEID ", " BVBA ", 1)
replace `var' = subinstr( `var', " COMMANDITAIRE VENNOOTSCHAP OP AANDELEN ", " CVA ", 1)
replace `var' = subinstr( `var', " GEWONE COMMANDITAIRE VENNOOTSCHAP ", " GCV ", 1)
replace `var' = subinstr( `var', " SOCIETE EN COMMANDITE PAR ACTIONS ", " SCA ", 1)

** DENMARK
* Usually danish identifiers have a slash (eg. A/S or K/S), but these will have been removed with all
* other punctuation earlier (so just use AS or KS).
replace `var' = subinstr( `var', " ANDELSSELSKABET ", " AMBA ", 1)
replace `var' = subinstr( `var', " ANDELSSELSKAB ", " AMBA ", 1)
replace `var' = subinstr( `var', " INTERESSENTSKABET ", " IS ", 1)
replace `var' = subinstr( `var', " INTERESSENTSKAB ", " IS ", 1)
replace `var' = subinstr( `var', " KOMMANDITAKTIESELSKABET ", " KAS ", 1)
replace `var' = subinstr( `var', " KOMMANDITAKTIESELSKAB ", " KAS ", 1)
replace `var' = subinstr( `var', " KOMMANDITSELSKABET ", " KS ", 1)
replace `var' = subinstr( `var', " KOMMANDITSELSKAB ", " KS ", 1)

** NORWAY
replace `var' = subinstr( `var', " ANDELSLAGET ", " AL ", 1)
replace `var' = subinstr( `var', " ANDELSLAG ", " AL ", 1)
replace `var' = subinstr( `var', " ANSVARLIG SELSKAPET ", " ANS ", 1)
replace `var' = subinstr( `var', " ANSVARLIG SELSKAP ", " ANS ", 1)
replace `var' = subinstr( `var', " AKSJESELSKAPET ", " AS ", 1)
replace `var' = subinstr( `var', " AKSJESELSKAP ", " AS ", 1)
replace `var' = subinstr( `var', " ALLMENNAKSJESELSKAPET ", " ASA ", 1)
replace `var' = subinstr( `var', " ALLMENNAKSJESELSKAP ", " ASA ", 1)
replace `var' = subinstr( `var', " SELSKAP MED DELT ANSAR ", " DA ", 1)
replace `var' = subinstr( `var', " KOMMANDITTSELSKAPET ", " KS ", 1)
replace `var' = subinstr( `var', " KOMMANDITTSELSKAP ", " KS ", 1)

** NETHERLANDS
replace `var' = subinstr( `var', " COMMANDITAIRE VENNOOTSCHAP ", " CV ", 1)
replace `var' = subinstr( `var', " COMMANDITAIRE VENNOOTSCHAP OP ANDELEN ", " CVOA ", 1)
replace `var' = subinstr( `var', " VENNOOTSCHAP ONDER FIRMA ", " VOF ", 1)

** FINLAND
replace `var' = subinstr( `var', " PUBLIKT AKTIEBOLAG ", " APB ", 1)
replace `var' = subinstr( `var', " KOMMANDIITTIYHTIO ", " KY ", 1)
replace `var' = subinstr( `var', " JULKINEN OSAKEYHTIO ", " OYJ ", 1)

** POLAND
replace `var' = subinstr( `var', " SPOLKA AKCYJNA ", " SA ", 1) 
replace `var' = subinstr( `var', " SPOLKA PRAWA CYWILNEGO ", " SC ", 1)
replace `var' = subinstr( `var', " SPOLKA KOMANDYTOWA ", " SK ", 1)
replace `var' = subinstr( `var', " SPOLKA Z OGRANICZONA ODPOWIEDZIALNOSCIA ", " SPZOO ", 1)
replace `var' = subinstr( `var', " SP Z OO ", " SPZOO ", 1)
replace `var' = subinstr( `var', " SPZ OO ", " SPZOO ", 1)
replace `var' = subinstr( `var', " SP ZOO ", " SPZOO ", 1)

** GREECE
replace `var' = subinstr( `var', " ANONYMOS ETAIRIA ", " AE ", 1)
replace `var' = subinstr( `var', " ETERRORRYTHMOS ", " EE ", 1)
replace `var' = subinstr( `var', " ETAIRIA PERIORISMENIS EVTHINIS ", " EPE ", 1)
replace `var' = subinstr( `var', " OMORRYTHMOS ", " OE ", 1)

** CZECH REPUBLIC
replace `var' = subinstr( `var', " AKCIOVA SPOLECNOST ", " AS ", 1)
replace `var' = subinstr( `var', " KOMANDITNI SPOLECNOST ", " KS ", 1)
replace `var' = subinstr( `var', " SPOLECNOST S RUCENIM OMEZENYM ", " SRO ", 1)
replace `var' = subinstr( `var', " VEREJNA OBCHODNI SPOLECNOST ", " VOS ", 1) 
                
** BULGARIA
replace `var' = subinstr( `var', " AKTIONIERNO DRUSHESTWO ", " AD ", 1)
replace `var' = subinstr( `var', " KOMANDITNO DRUSHESTWO ", " KD ", 1)
replace `var' = subinstr( `var', " KOMANDITNO DRUSHESTWO S AKZII ", " KDA ", 1)
replace `var' = subinstr( `var', " DRUSHESTWO S ORGRANITSCHENA OTGOWORNOST ", " OCD ", 1)

}

//delete empty spaces
replace standard_name_patent = subinstr(standard_name_patent, " ", "", .)

drop assignee_id location_id

save "_matching\Patent Daten\assignee_clean2.dta", replace


*-DEFINE SAMPLE-----------------------------------------------------------------

*Load geo-matched data (mapping patent applicants to NETS HQ in same area)
use "_matching\patent link NETS\matched_patents.dta", clear
keep firm_id hqduns
 
*Add back names of patent applicants and NETS HQ
merge m:1 firm_id using "_matching\Patent Daten\assignee_clean2.dta", keepusing(standard_name_patent latitude_assignee longitude_assignee) 
	keep if _merge == 3	// 310,005 obs dropped
	drop _merge

merge m:1 hqduns using "NETS\Geocoding\NETS2022_addresses_geocoded_all.dta", keepusing(hqcompany lon lat) 
	keep if _merge == 3	// 294,457 obs dropped
	drop _merge

save "_matching\patent link NETS\matched_patents_names.dta", replace	
	
*-MATCHING OF FIRMS-------------------------------------------------------------

use  "_matching\patent link NETS\matched_patents_names.dta", clear
	
*Check whether there are any exact matches for coordinates 
// Before that, we have to unify the length of lon and lat 
gen lon_str = string(lonNETS) 
gen lon_short = ""
replace lon_short = substr(lon_str,1,8)
destring lon_short, replace
drop lon_str
gen lat_str = string(latNETS) 
gen lat_short = ""
replace lat_short = substr(lat_str,1,7)
destring lat_short, replace
drop lat_str

/*
// Now, let's look for exact matches
gen match = .
replace match = 1 if latitude_assignee == lat_short & longitude_assignee == lon_short
// There are none ¯\_(ツ)_/¯
drop match
*/
*Conduct name matching for firms in close proximity

matchit standard_name_patent hqcompany

save "_matching\patent link NETS\matchresult_patent_NETS.dta", replace	

keep if similscore > 0.7

save "_matching\patent link NETS\matchresult_patent_NETS_red.dta", replace